// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#ifndef _320X240_UI_H
#define _320X240_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

//#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_MonitorPanel;
extern lv_obj_t * ui_Extruder1;
extern lv_obj_t * ui_Extruder1Text;
extern lv_obj_t * ui_Extruder1Image;
extern lv_obj_t * ui_Extruder1Temp;
extern lv_obj_t * ui_Extruder2;
extern lv_obj_t * ui_Extruder2Text;
extern lv_obj_t * ui_Extruder2Image;
extern lv_obj_t * ui_Extruder2Temp;
extern lv_obj_t * ui_Fan1;
extern lv_obj_t * ui_Fan1Temp;
extern lv_obj_t * ui_Extruder2Temp3;
extern lv_obj_t * ui_Fan2;
extern lv_obj_t * ui_Fan2Temp;
extern lv_obj_t * ui_Extruder2Temp4;
extern lv_obj_t * ui_PositionX;
extern lv_obj_t * ui_PositonXText;
extern lv_obj_t * ui_PositonXText1;
extern lv_obj_t * ui_PositionY;
extern lv_obj_t * ui_PositonYText;
extern lv_obj_t * ui_PositonYText1;
extern lv_obj_t * ui_Extruder1Speed;
extern lv_obj_t * ui_Extruder1SpeedText;
extern lv_obj_t * ui_Extruder1SpeedText1;
extern lv_obj_t * ui_Extruder2Speed;
extern lv_obj_t * ui_Extruder2SpeedText;
extern lv_obj_t * ui_Extruder2SpeedText1;
void ui_event_AxisButton(lv_event_t * e);
extern lv_obj_t * ui_AxisButton;
extern lv_obj_t * ui_AxisLable;
void ui_event_TempButton(lv_event_t * e);
extern lv_obj_t * ui_TempButton;
extern lv_obj_t * ui_TempLable;
extern lv_obj_t * ui_CalibrationButton;
extern lv_obj_t * ui_CalibrationLable;
extern lv_obj_t * ui_SettingButton;
extern lv_obj_t * ui_SettingLable;
// CUSTOM VARIABLES
void ui_event_CalibrationButton(lv_event_t * e); //系统初始化

// SCREEN: ui_AxisScreen
void ui_AxisScreen_screen_init(void);
extern lv_obj_t * ui_AxisScreen;
extern lv_obj_t * ui_HeadText1;
extern lv_obj_t * ui_HeadText2;
extern lv_obj_t * ui_Up1Button1;
extern lv_obj_t * ui_Label1mmUp1;
extern lv_obj_t * ui_Up1Button2;
extern lv_obj_t * ui_Label5mmUp1;
extern lv_obj_t * ui_Up1Button3;
extern lv_obj_t * ui_Label10mmUp1;
extern lv_obj_t * ui_Down1Button1;
extern lv_obj_t * ui_Label1mmDown1;
extern lv_obj_t * ui_Down1Button2;
extern lv_obj_t * ui_Label5mmDown1;
extern lv_obj_t * ui_Down1Button3;
extern lv_obj_t * ui_Label10mmDown1;
extern lv_obj_t * ui_CutButton;
extern lv_obj_t * ui_CutLabel;
extern lv_obj_t * ui_Up2Button1;
extern lv_obj_t * ui_Label1mmUp2;
extern lv_obj_t * ui_Up2Button2;
extern lv_obj_t * ui_Label5mmUp2;
extern lv_obj_t * ui_Up2Button3;
extern lv_obj_t * ui_Label10mmUp2;
extern lv_obj_t * ui_Down2Button1;
extern lv_obj_t * ui_Label1mmDown2;
extern lv_obj_t * ui_Down2Button2;
extern lv_obj_t * ui_Label5mmDown2;
extern lv_obj_t * ui_Down2Button3;
extern lv_obj_t * ui_Label10mmDown2;
void ui_event_ResetButton1(lv_event_t * e);
extern lv_obj_t * ui_ResetButton1;
extern lv_obj_t * ui_ResetText1;
void ui_event_ResetButton2(lv_event_t * e);
extern lv_obj_t * ui_ResetButton2;
extern lv_obj_t * ui_ResetText2;
extern lv_obj_t * ui_CutterResetButton;
extern lv_obj_t * ui_ResetCutter;
extern lv_obj_t * ui_CutterDownButton;
extern lv_obj_t * ui_CutterDown;
extern lv_obj_t * ui_CutterUp1mm;
extern lv_obj_t * ui_CutterUp1mmLabel;
extern lv_obj_t * ui_CutterUp5mm;
extern lv_obj_t * ui_CutterUp5mmLabel;
extern lv_obj_t * ui_CutterDn1mm;
extern lv_obj_t * ui_CutterDn1mmLabel;
extern lv_obj_t * ui_CutterDn5mm;
extern lv_obj_t * ui_CutterDn5mmLabel;
void ui_event_Set1Button(lv_event_t * e);
extern lv_obj_t * ui_Set1Button;
extern lv_obj_t * ui_Set1Text;
void ui_event_Set2Button(lv_event_t * e);
extern lv_obj_t * ui_Set2Button;
extern lv_obj_t * ui_Set2Text;
void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_HomeLable2;
extern lv_obj_t * ui_HomeImage2;
extern lv_obj_t * ui_CutterStopButton;
extern lv_obj_t * ui_CutterStopText;
// CUSTOM VARIABLES
void ui_event_CutterStopButton(lv_event_t * e);
void ui_event_CutterResetButton(lv_event_t * e);
void ui_event_CutterDownButton(lv_event_t * e);
void ui_event_Up1Button1(lv_event_t * e);
void ui_event_Up1Button2(lv_event_t * e);
void ui_event_Up1Button3(lv_event_t * e);
void ui_event_Down1Button1(lv_event_t * e);
void ui_event_Down1Button2(lv_event_t * e);
void ui_event_Down1Button3(lv_event_t * e);
void ui_event_Up2Button1(lv_event_t * e);
void ui_event_Up2Button2(lv_event_t * e);
void ui_event_Up2Button3(lv_event_t * e);
void ui_event_Down2Button1(lv_event_t * e);
void ui_event_Down2Button2(lv_event_t * e);
void ui_event_Down2Button3(lv_event_t * e);

// SCREEN: ui_TempScreen
void ui_TempScreen_screen_init(void);
extern lv_obj_t * ui_TempScreen;
void ui_event_SetTemp(lv_event_t * e);
extern lv_obj_t * ui_SetTemp;
extern lv_obj_t * ui_SetTempText;
extern lv_obj_t * ui_SetExtruderTempPanel;
extern lv_obj_t * ui_Keyboard1;
void ui_event_T1Enter1(lv_event_t * e);
extern lv_obj_t * ui_T1Enter1;
void ui_event_T2Enter1(lv_event_t * e);
extern lv_obj_t * ui_T2Enter1;
extern lv_obj_t * ui_ApplyButton1;
extern lv_obj_t * ui_LabelApplyT1;
extern lv_obj_t * ui_ApplyButton2;
extern lv_obj_t * ui_LabelApplyT2;
void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_LabelBack;
void ui_event_V1Enter(lv_event_t * e);
extern lv_obj_t * ui_V1Enter;
void ui_event_V2Enter(lv_event_t * e);
extern lv_obj_t * ui_V2Enter;
extern lv_obj_t * ui_ApplyButton4;
extern lv_obj_t * ui_LabelApplyT4;
extern lv_obj_t * ui_ApplyButton3;
extern lv_obj_t * ui_LabelApplyT3;
void ui_event_Vb1Enter(lv_event_t * e);
extern lv_obj_t * ui_Vb1Enter;
extern lv_obj_t * ui_ApplyButton5;
extern lv_obj_t * ui_LabelApplyT5;
void ui_event_Vb2Enter(lv_event_t * e);
extern lv_obj_t * ui_Vb2Enter;
extern lv_obj_t * ui_ApplyButton6;
extern lv_obj_t * ui_LabelApplyT6;
extern lv_obj_t * ui_Fan1Button2;
extern lv_obj_t * ui_Fan1OFLabel2;
extern lv_obj_t * ui_Fan2Button2;
extern lv_obj_t * ui_Fan2OFLabel3;
void ui_event_HomeButton3(lv_event_t * e);
extern lv_obj_t * ui_HomeButton3;
extern lv_obj_t * ui_HomeLable3;
extern lv_obj_t * ui_HomeImage3;
extern lv_obj_t * ui_Extruder4;
extern lv_obj_t * ui_Extruder1Text2;
extern lv_obj_t * ui_Extruder1Image2;
extern lv_obj_t * ui_Extruder1Status;
extern lv_obj_t * ui_Extruder5;
extern lv_obj_t * ui_Extruder2Text2;
extern lv_obj_t * ui_Extruder2Image2;
extern lv_obj_t * ui_Extruder2Status;
extern lv_obj_t * ui_HeadText4;
extern lv_obj_t * ui_HeadText5;
extern lv_obj_t * ui_GoButton1;
extern lv_obj_t * ui_Label10mmUp4;
extern lv_obj_t * ui_GoBackButton1;
extern lv_obj_t * ui_Label10mmUp5;
extern lv_obj_t * ui_StopButton1;
extern lv_obj_t * ui_Label10mmUp6;
extern lv_obj_t * ui_GoButton2;
extern lv_obj_t * ui_Label10mmUp7;
extern lv_obj_t * ui_GoBackButton2;
extern lv_obj_t * ui_Label10mmUp8;
extern lv_obj_t * ui_StopButton5;
extern lv_obj_t * ui_Label10mmUp9;
// CUSTOM VARIABLES
void ui_event_GoButton1(lv_event_t * e);
void ui_event_GoBackButton1(lv_event_t * e);
void ui_event_StopButton1(lv_event_t * e);
void ui_event_GoButton2(lv_event_t * e);
void ui_event_GoBackButton2(lv_event_t * e);
void ui_event_StopButton5(lv_event_t * e);
void ui_event_Fan1Button2(lv_event_t * e);
void ui_event_Fan2Button2(lv_event_t * e);
void ui_event_SetTemp(lv_event_t * e);
void ui_event_ApplyButton1(lv_event_t * e);
void ui_event_ApplyButton2(lv_event_t * e);
void ui_event_ApplyButton3(lv_event_t * e);
void ui_event_ApplyButton4(lv_event_t * e);
void ui_event_ApplyButton5(lv_event_t * e);
void ui_event_ApplyButton6(lv_event_t * e);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_browser_extruder3_png);    // assets/Browser_extruder3.png
LV_IMG_DECLARE(ui_img_browser_extruder1_png);    // assets/Browser_extruder1.png
LV_IMG_DECLARE(ui_img_home_fill_png);    // assets/home_fill.png
LV_IMG_DECLARE(ui_img_browser_extruder2_png);    // assets/Browser_extruder2.png
LV_IMG_DECLARE(ui_img_fan1_png);    // assets/fan1.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
