// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "../ui.h"

#include <stdio.h>

#include "fan.h"
#include "temperature.h"

//extern float get_temperature1();
//extern float get_temperature2();
//extern bool fan_get_state(fan_id_t id);

// UI 更新回调
static void update_ui_per_second_cb(lv_timer_t *timer) 
{
    char buf[32]; 

    //纤维头温度
    float t1 = get_temperature1();
    snprintf(buf, sizeof(buf), "%.0f", t1);
    lv_label_set_text(ui_Extruder1Temp, buf);

    //树脂头温度
    float t2 = get_temperature2();
    snprintf(buf, sizeof(buf), "%.0f", t2);
    lv_label_set_text(ui_Extruder2Temp, buf);

    //纤维风扇状态
    bool is_fan1_on = fan_get_state(FAN1);
    if (is_fan1_on) {
        lv_label_set_text(ui_Extruder2Temp3, "ON");
    } else {
        lv_label_set_text(ui_Extruder2Temp3, "OFF");
    }

    //树脂风扇状态
    bool is_fan2_on = fan_get_state(FAN2);
    if (is_fan2_on) {
        lv_label_set_text(ui_Extruder2Temp4, "ON");
    } else {
        lv_label_set_text(ui_Extruder2Temp4, "OFF");
    }
}



void ui_HomeScreen_screen_init(void)
{
    lv_timer_create(update_ui_per_second_cb, 1000, NULL);//温度+风扇状态更新

    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_HomeButton, 40);
    lv_obj_set_height(ui_HomeButton, 106);
    lv_obj_set_x(ui_HomeButton, -220);
    lv_obj_set_y(ui_HomeButton, -110);
    lv_obj_set_align(ui_HomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLable = lv_label_create(ui_HomeButton);
    lv_obj_set_width(ui_HomeLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLable, 0);
    lv_obj_set_y(ui_HomeLable, -15);
    lv_obj_set_align(ui_HomeLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLable, "主页");
    lv_obj_set_style_text_color(ui_HomeLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage = lv_img_create(ui_HomeButton);
    lv_img_set_src(ui_HomeImage, &ui_img_home_fill_png);
    lv_obj_set_width(ui_HomeImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage, 0);
    lv_obj_set_y(ui_HomeImage, 10);
    lv_obj_set_align(ui_HomeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HomeImage, 30);

    ui_PowerButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_PowerButton, 40);
    lv_obj_set_height(ui_PowerButton, 106);
    lv_obj_set_x(ui_PowerButton, -220);
    lv_obj_set_y(ui_PowerButton, 0);
    lv_obj_set_align(ui_PowerButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PowerButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PowerButton, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_StopButton, 40);
    lv_obj_set_height(ui_StopButton, 106);
    lv_obj_set_x(ui_StopButton, -220);
    lv_obj_set_y(ui_StopButton, 110);
    lv_obj_set_align(ui_StopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLable = lv_label_create(ui_StopButton);
    lv_obj_set_width(ui_StopLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StopLable, 0);
    lv_obj_set_y(ui_StopLable, -20);
    lv_obj_set_align(ui_StopLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLable, "紧急\n停止");
    lv_obj_set_style_text_color(ui_StopLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopImage = lv_img_create(ui_StopButton);
    lv_img_set_src(ui_StopImage, &ui_img_emergency_png);
    lv_obj_set_width(ui_StopImage, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_StopImage, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_StopImage, 0);
    lv_obj_set_y(ui_StopImage, 15);
    lv_obj_set_align(ui_StopImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StopImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_StopImage, 30);

    ui_ProcessPanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_ProcessPanel, 200);
    lv_obj_set_height(ui_ProcessPanel, 80);
    lv_obj_set_x(ui_ProcessPanel, -75);
    lv_obj_set_y(ui_ProcessPanel, 100);
    lv_obj_set_align(ui_ProcessPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProcessPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProcessPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProcessPanel, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProcessPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ProcessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FileName = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_FileName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FileName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FileName, -45);
    lv_obj_set_y(ui_FileName, -20);
    lv_obj_set_align(ui_FileName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FileName, "文件名称：");
    lv_obj_set_style_text_font(ui_FileName, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartTime = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_StartTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartTime, -45);
    lv_obj_set_y(ui_StartTime, 0);
    lv_obj_set_align(ui_StartTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartTime, "开始时间：");
    lv_obj_set_style_text_font(ui_StartTime, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Progress = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_Progress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Progress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Progress, -45);
    lv_obj_set_y(ui_Progress, 20);
    lv_obj_set_align(ui_Progress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Progress, "打印进度：");
    lv_obj_set_style_text_font(ui_Progress, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FileNameText = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_FileNameText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FileNameText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FileNameText, 40);
    lv_obj_set_y(ui_FileNameText, -20);
    lv_obj_set_align(ui_FileNameText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FileNameText, "1");
    lv_obj_set_style_text_font(ui_FileNameText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartTimeText = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_StartTimeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartTimeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartTimeText, 40);
    lv_obj_set_y(ui_StartTimeText, 0);
    lv_obj_set_align(ui_StartTimeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartTimeText, "2");
    lv_obj_set_style_text_font(ui_StartTimeText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgressText = lv_label_create(ui_ProcessPanel);
    lv_obj_set_width(ui_ProgressText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgressText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgressText, 40);
    lv_obj_set_y(ui_ProgressText, 20);
    lv_obj_set_align(ui_ProgressText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgressText, "3");
    lv_obj_set_style_text_font(ui_ProgressText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonitorPanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_MonitorPanel, 200);
    lv_obj_set_height(ui_MonitorPanel, 160);
    lv_obj_set_x(ui_MonitorPanel, -75);
    lv_obj_set_y(ui_MonitorPanel, -55);
    lv_obj_set_align(ui_MonitorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MonitorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MonitorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MonitorPanel, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MonitorPanel, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MonitorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder1, 180);
    lv_obj_set_height(ui_Extruder1, 30);
    lv_obj_set_x(ui_Extruder1, 0);
    lv_obj_set_y(ui_Extruder1, -60);
    lv_obj_set_align(ui_Extruder1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Text = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Extruder1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Text, -10);
    lv_obj_set_y(ui_Extruder1Text, 0);
    lv_obj_set_align(ui_Extruder1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Text, "纤维挤出头");
    lv_obj_set_style_text_align(ui_Extruder1Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Image = lv_img_create(ui_Extruder1);
    lv_img_set_src(ui_Extruder1Image, &ui_img_browser_extruder3_png);
    lv_obj_set_width(ui_Extruder1Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder1Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder1Image, -70);
    lv_obj_set_y(ui_Extruder1Image, 0);
    lv_obj_set_align(ui_Extruder1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder1Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder1Image, 20);

    ui_Extruder1Temp = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Extruder1Temp, 35);
    lv_obj_set_height(ui_Extruder1Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Temp, 60);
    lv_obj_set_y(ui_Extruder1Temp, 0);
    lv_obj_set_align(ui_Extruder1Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Temp, "T1");//纤维头温度
    lv_obj_set_style_text_align(ui_Extruder1Temp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder2, 180);
    lv_obj_set_height(ui_Extruder2, 30);
    lv_obj_set_x(ui_Extruder2, 0);
    lv_obj_set_y(ui_Extruder2, -20);
    lv_obj_set_align(ui_Extruder2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Text = lv_label_create(ui_Extruder2);
    lv_obj_set_width(ui_Extruder2Text, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Extruder2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Text, -10);
    lv_obj_set_y(ui_Extruder2Text, 0);
    lv_obj_set_align(ui_Extruder2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Text, "树脂挤出头");
    lv_obj_set_style_text_align(ui_Extruder2Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Image = lv_img_create(ui_Extruder2);
    lv_img_set_src(ui_Extruder2Image, &ui_img_browser_extruder1_png);
    lv_obj_set_width(ui_Extruder2Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder2Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder2Image, -70);
    lv_obj_set_y(ui_Extruder2Image, 0);
    lv_obj_set_align(ui_Extruder2Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder2Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder2Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder2Image, 20);

    ui_Extruder2Temp = lv_label_create(ui_Extruder2);
    lv_obj_set_width(ui_Extruder2Temp, 35);
    lv_obj_set_height(ui_Extruder2Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp, 60);
    lv_obj_set_y(ui_Extruder2Temp, 0);
    lv_obj_set_align(ui_Extruder2Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp, "T2"); //树脂头温度
    lv_obj_set_style_text_align(ui_Extruder2Temp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Fan1, 180);
    lv_obj_set_height(ui_Fan1, 30);
    lv_obj_set_x(ui_Fan1, 0);
    lv_obj_set_y(ui_Fan1, 20);
    lv_obj_set_align(ui_Fan1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Fan1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Fan1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Fan1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1Temp = lv_label_create(ui_Fan1);
    lv_obj_set_width(ui_Fan1Temp, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Fan1Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan1Temp, -10);
    lv_obj_set_y(ui_Fan1Temp, 0);
    lv_obj_set_align(ui_Fan1Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan1Temp, "纤维头风扇");
    lv_obj_set_style_text_align(ui_Fan1Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan1Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1Image = lv_img_create(ui_Fan1);
    lv_img_set_src(ui_Fan1Image, &ui_img_fan_png);
    lv_obj_set_width(ui_Fan1Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Fan1Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Fan1Image, -70);
    lv_obj_set_y(ui_Fan1Image, 0);
    lv_obj_set_align(ui_Fan1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan1Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Fan1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Fan1Image, 20);

    ui_Extruder2Temp3 = lv_label_create(ui_Fan1);
    lv_obj_set_width(ui_Extruder2Temp3, 35);
    lv_obj_set_height(ui_Extruder2Temp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp3, 60);
    lv_obj_set_y(ui_Extruder2Temp3, 0);
    lv_obj_set_align(ui_Extruder2Temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp3, "T4");
    lv_obj_set_style_text_align(ui_Extruder2Temp3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Fan2, 180);
    lv_obj_set_height(ui_Fan2, 30);
    lv_obj_set_x(ui_Fan2, 0);
    lv_obj_set_y(ui_Fan2, 60);
    lv_obj_set_align(ui_Fan2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Fan2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Fan2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Fan2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2Temp = lv_label_create(ui_Fan2);
    lv_obj_set_width(ui_Fan2Temp, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Fan2Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan2Temp, -10);
    lv_obj_set_y(ui_Fan2Temp, 0);
    lv_obj_set_align(ui_Fan2Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan2Temp, "树脂头风扇");
    lv_obj_set_style_text_align(ui_Fan2Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan2Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2Image = lv_img_create(ui_Fan2);
    lv_img_set_src(ui_Fan2Image, &ui_img_fan1_png);
    lv_obj_set_width(ui_Fan2Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Fan2Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Fan2Image, -70);
    lv_obj_set_y(ui_Fan2Image, 0);
    lv_obj_set_align(ui_Fan2Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan2Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Fan2Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Fan2Image, 20);

    ui_Extruder2Temp4 = lv_label_create(ui_Fan2);
    lv_obj_set_width(ui_Extruder2Temp4, 35);
    lv_obj_set_height(ui_Extruder2Temp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp4, 60);
    lv_obj_set_y(ui_Extruder2Temp4, 0);
    lv_obj_set_align(ui_Extruder2Temp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp4, "T5");
    lv_obj_set_style_text_align(ui_Extruder2Temp4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AxisButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_AxisButton, 90);
    lv_obj_set_height(ui_AxisButton, 90);
    lv_obj_set_x(ui_AxisButton, 75);
    lv_obj_set_y(ui_AxisButton, -100);
    lv_obj_set_align(ui_AxisButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AxisButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AxisButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AxisButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AxisButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AxisButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AxisButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AxisLable = lv_label_create(ui_AxisButton);
    lv_obj_set_width(ui_AxisLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AxisLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AxisLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AxisLable, "位置校准");
    lv_obj_set_style_text_font(ui_AxisLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_TempButton, 90);
    lv_obj_set_height(ui_TempButton, 90);
    lv_obj_set_x(ui_TempButton, 175);
    lv_obj_set_y(ui_TempButton, -100);
    lv_obj_set_align(ui_TempButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLable = lv_label_create(ui_TempButton);
    lv_obj_set_width(ui_TempLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLable, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_TempLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLable, "温度与挤出\n调整");
    lv_obj_set_style_text_align(ui_TempLable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_CalibrationButton, 90);
    lv_obj_set_height(ui_CalibrationButton, 90);
    lv_obj_set_x(ui_CalibrationButton, 75);
    lv_obj_set_y(ui_CalibrationButton, 0);
    lv_obj_set_align(ui_CalibrationButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalibrationButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibrationButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibrationButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CalibrationButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationLable = lv_label_create(ui_CalibrationButton);
    lv_obj_set_width(ui_CalibrationLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationLable, "初始化");
    lv_obj_set_style_text_font(ui_CalibrationLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_SettingButton, 90);
    lv_obj_set_height(ui_SettingButton, 90);
    lv_obj_set_x(ui_SettingButton, 175);
    lv_obj_set_y(ui_SettingButton, 0);
    lv_obj_set_align(ui_SettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingLable = lv_label_create(ui_SettingButton);
    lv_obj_set_width(ui_SettingLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingLable, "设置");
    lv_obj_set_style_text_font(ui_SettingLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_StartButton, 150);
    lv_obj_set_height(ui_StartButton, 45);
    lv_obj_set_x(ui_StartButton, 125);
    lv_obj_set_y(ui_StartButton, 100);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLable = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_StartLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLable, "开始打印");
    lv_obj_set_style_text_font(ui_StartLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AxisButton, ui_event_AxisButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempButton, ui_event_TempButton, LV_EVENT_ALL, NULL);

}
