// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "../ui.h"

#include <stdio.h>
#include <stdlib.h> 
#include <string.h>

#include "fan.h"
#include "temperature.h"

// UI 更新回调
static void update_ui_per_second_cb(lv_timer_t *timer) 
{
    char buf[32]; 

    //纤维头温度
    float t1 = get_temperature1();
    snprintf(buf, sizeof(buf), "%.0f", t1);
    lv_label_set_text(ui_Extruder1Temp2, buf);

    //树脂头温度
    float t2 = get_temperature2();
    snprintf(buf, sizeof(buf), "%.0f", t2);
    lv_label_set_text(ui_Extruder2Temp5, buf);

    //纤维风扇状态
    bool is_fan1_on = fan_get_state(FAN1);
    // if (is_fan1_on) {
    //     lv_label_set_text(ui_Extruder2Temp3, "ON");
    // } else {
    //     lv_label_set_text(ui_Extruder2Temp3, "OFF");
    // }

    //树脂风扇状态
    bool is_fan2_on = fan_get_state(FAN2);
    // if (is_fan2_on) {
    //     lv_label_set_text(ui_Extruder2Temp4, "ON");
    // } else {
    //     lv_label_set_text(ui_Extruder2Temp4, "OFF");
    // }
}


void ui_TempScreen_screen_init(void)
{
    lv_timer_create(update_ui_per_second_cb, 1000, NULL);//温度+风扇状态更新

    ui_TempScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TempScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempScreen, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTemp = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_SetTemp, 100);
    lv_obj_set_height(ui_SetTemp, 40);
    lv_obj_set_x(ui_SetTemp, 135);
    lv_obj_set_y(ui_SetTemp, -100);
    lv_obj_set_align(ui_SetTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTempText = lv_label_create(ui_SetTemp);
    lv_obj_set_width(ui_SetTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTempText, "设定挤出头\n温度");
    lv_obj_set_style_text_align(ui_SetTempText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTempText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetExtruderTempPanel = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_SetExtruderTempPanel, 380);
    lv_obj_set_height(ui_SetExtruderTempPanel, 162);
    lv_obj_set_x(ui_SetExtruderTempPanel, 20);
    lv_obj_set_y(ui_SetExtruderTempPanel, -75);
    lv_obj_set_align(ui_SetExtruderTempPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetExtruderTempPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SetExtruderTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetExtruderTempPanel, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetExtruderTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetExtruderTempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetExtruderTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetExtruderTempPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_SetExtruderTempPanel);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 249);
    lv_obj_set_height(ui_Keyboard1, 105);
    lv_obj_set_x(ui_Keyboard1, -57);
    lv_obj_set_y(ui_Keyboard1, 22);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Keyboard1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Keyboard1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_T1Enter1 = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_T1Enter1, 150);
    lv_obj_set_height(ui_T1Enter1, 40);
    lv_obj_set_x(ui_T1Enter1, -100);
    lv_obj_set_y(ui_T1Enter1, -53);
    lv_obj_set_align(ui_T1Enter1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_T1Enter1, "输入纤维加热温度");
    lv_obj_set_style_text_font(ui_T1Enter1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_T1Enter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_T1Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_T1Enter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_T1Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_T2Enter1 = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_T2Enter1, 150);
    lv_obj_set_height(ui_T2Enter1, 40);
    lv_obj_set_x(ui_T2Enter1, 100);
    lv_obj_set_y(ui_T2Enter1, -54);
    lv_obj_set_align(ui_T2Enter1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_T2Enter1, "输入树脂加热温度");
    lv_obj_set_style_text_font(ui_T2Enter1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_T2Enter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_T2Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_T2Enter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_T2Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ApplyButton1 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton1, 100);
    lv_obj_set_height(ui_ApplyButton1, 20);
    lv_obj_set_x(ui_ApplyButton1, 130);
    lv_obj_set_y(ui_ApplyButton1, -15);
    lv_obj_set_align(ui_ApplyButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT1 = lv_label_create(ui_ApplyButton1);
    lv_obj_set_width(ui_LabelApplyT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT1, "确认纤维温度");
    lv_obj_set_style_text_color(ui_LabelApplyT1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ApplyButton2 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton2, 100);
    lv_obj_set_height(ui_ApplyButton2, 23);
    lv_obj_set_x(ui_ApplyButton2, 130);
    lv_obj_set_y(ui_ApplyButton2, 20);
    lv_obj_set_align(ui_ApplyButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT2 = lv_label_create(ui_ApplyButton2);
    lv_obj_set_width(ui_LabelApplyT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT2, "确认树脂温度");
    lv_obj_set_style_text_color(ui_LabelApplyT2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_BackButton, 65);
    lv_obj_set_height(ui_BackButton, 23);
    lv_obj_set_x(ui_BackButton, 130);
    lv_obj_set_y(ui_BackButton, 56);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x202123), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBack = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_LabelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack, "返回");
    lv_obj_set_style_text_color(ui_LabelBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1Button2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_Fan1Button2, 80);
    lv_obj_set_height(ui_Fan1Button2, 40);
    lv_obj_set_x(ui_Fan1Button2, 90);
    lv_obj_set_y(ui_Fan1Button2, -40);
    lv_obj_set_align(ui_Fan1Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan1Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fan1Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fan1Button2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan1Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1OFLabel2 = lv_label_create(ui_Fan1Button2);
    lv_obj_set_width(ui_Fan1OFLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan1OFLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fan1OFLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan1OFLabel2, "纤维风扇\n开/关");
    lv_obj_set_style_text_align(ui_Fan1OFLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan1OFLabel2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2Button2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_Fan2Button2, 80);
    lv_obj_set_height(ui_Fan2Button2, 40);
    lv_obj_set_x(ui_Fan2Button2, 180);
    lv_obj_set_y(ui_Fan2Button2, -40);
    lv_obj_set_align(ui_Fan2Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan2Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fan2Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fan2Button2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2OFLabel3 = lv_label_create(ui_Fan2Button2);
    lv_obj_set_width(ui_Fan2OFLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan2OFLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fan2OFLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan2OFLabel3, "树脂风扇\n开/关");
    lv_obj_set_style_text_align(ui_Fan2OFLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan2OFLabel3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton3 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_HomeButton3, 40);
    lv_obj_set_height(ui_HomeButton3, 106);
    lv_obj_set_x(ui_HomeButton3, -220);
    lv_obj_set_y(ui_HomeButton3, -110);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLable3 = lv_label_create(ui_HomeButton3);
    lv_obj_set_width(ui_HomeLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLable3, 0);
    lv_obj_set_y(ui_HomeLable3, -15);
    lv_obj_set_align(ui_HomeLable3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLable3, "主页");
    lv_obj_set_style_text_color(ui_HomeLable3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLable3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLable3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage3 = lv_img_create(ui_HomeButton3);
    lv_img_set_src(ui_HomeImage3, &ui_img_home_fill_png);
    lv_obj_set_width(ui_HomeImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage3, 0);
    lv_obj_set_y(ui_HomeImage3, 10);
    lv_obj_set_align(ui_HomeImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HomeImage3, 30);

    ui_PowerButton3 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_PowerButton3, 40);
    lv_obj_set_height(ui_PowerButton3, 106);
    lv_obj_set_x(ui_PowerButton3, -220);
    lv_obj_set_y(ui_PowerButton3, 0);
    lv_obj_set_align(ui_PowerButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PowerButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PowerButton3, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton3 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_StopButton3, 40);
    lv_obj_set_height(ui_StopButton3, 106);
    lv_obj_set_x(ui_StopButton3, -220);
    lv_obj_set_y(ui_StopButton3, 110);
    lv_obj_set_align(ui_StopButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopButton3, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLable3 = lv_label_create(ui_StopButton3);
    lv_obj_set_width(ui_StopLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StopLable3, 0);
    lv_obj_set_y(ui_StopLable3, -20);
    lv_obj_set_align(ui_StopLable3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLable3, "紧急\n停止");
    lv_obj_set_style_text_color(ui_StopLable3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopLable3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopLable3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopImage3 = lv_img_create(ui_StopButton3);
    lv_img_set_src(ui_StopImage3, &ui_img_emergency_png);
    lv_obj_set_width(ui_StopImage3, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_StopImage3, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_StopImage3, 0);
    lv_obj_set_y(ui_StopImage3, 15);
    lv_obj_set_align(ui_StopImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StopImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_StopImage3, 30);

    ui_Extruder4 = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_Extruder4, 180);
    lv_obj_set_height(ui_Extruder4, 30);
    lv_obj_set_x(ui_Extruder4, -80);
    lv_obj_set_y(ui_Extruder4, -100);
    lv_obj_set_align(ui_Extruder4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder4, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Text2 = lv_label_create(ui_Extruder4);
    lv_obj_set_width(ui_Extruder1Text2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder1Text2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Text2, -10);
    lv_obj_set_y(ui_Extruder1Text2, 0);
    lv_obj_set_align(ui_Extruder1Text2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Text2, "纤维挤出头");
    lv_obj_set_style_text_align(ui_Extruder1Text2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Text2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Image2 = lv_img_create(ui_Extruder4);
    lv_img_set_src(ui_Extruder1Image2, &ui_img_browser_extruder3_png);
    lv_obj_set_width(ui_Extruder1Image2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder1Image2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder1Image2, -70);
    lv_obj_set_y(ui_Extruder1Image2, 0);
    lv_obj_set_align(ui_Extruder1Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder1Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder1Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder1Image2, 20);

    ui_Extruder1Temp2 = lv_label_create(ui_Extruder4);
    lv_obj_set_width(ui_Extruder1Temp2, 35);
    lv_obj_set_height(ui_Extruder1Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Temp2, 60);
    lv_obj_set_y(ui_Extruder1Temp2, 0);
    lv_obj_set_align(ui_Extruder1Temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Temp2, "T1");  //纤维头温度显示
    lv_obj_set_style_text_align(ui_Extruder1Temp2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Temp2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder5 = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_Extruder5, 180);
    lv_obj_set_height(ui_Extruder5, 30);
    lv_obj_set_x(ui_Extruder5, -80);
    lv_obj_set_y(ui_Extruder5, -50);
    lv_obj_set_align(ui_Extruder5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder5, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Text2 = lv_label_create(ui_Extruder5);
    lv_obj_set_width(ui_Extruder2Text2, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Extruder2Text2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Text2, -10);
    lv_obj_set_y(ui_Extruder2Text2, 0);
    lv_obj_set_align(ui_Extruder2Text2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Text2, "树脂挤出头");
    lv_obj_set_style_text_align(ui_Extruder2Text2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Text2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Image2 = lv_img_create(ui_Extruder5);
    lv_img_set_src(ui_Extruder2Image2, &ui_img_browser_extruder1_png);
    lv_obj_set_width(ui_Extruder2Image2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder2Image2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder2Image2, -70);
    lv_obj_set_y(ui_Extruder2Image2, 0);
    lv_obj_set_align(ui_Extruder2Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder2Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder2Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder2Image2, 20);

    ui_Extruder2Temp5 = lv_label_create(ui_Extruder5);
    lv_obj_set_width(ui_Extruder2Temp5, 35);
    lv_obj_set_height(ui_Extruder2Temp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp5, 60);
    lv_obj_set_y(ui_Extruder2Temp5, 0);
    lv_obj_set_align(ui_Extruder2Temp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp5, "T2"); //树脂头温度显示
    lv_obj_set_style_text_align(ui_Extruder2Temp5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText4 = lv_label_create(ui_TempScreen);
    lv_obj_set_width(ui_HeadText4, 215);
    lv_obj_set_height(ui_HeadText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText4, -90);
    lv_obj_set_y(ui_HeadText4, 150);
    lv_obj_set_align(ui_HeadText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText4, "纤维挤出头");
    lv_obj_set_style_text_align(ui_HeadText4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText4, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText5 = lv_label_create(ui_TempScreen);
    lv_obj_set_width(ui_HeadText5, 215);
    lv_obj_set_height(ui_HeadText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText5, 130);
    lv_obj_set_y(ui_HeadText5, 150);
    lv_obj_set_align(ui_HeadText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText5, "树脂挤出头");
    lv_obj_set_style_text_align(ui_HeadText5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText5, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoButton1, 50);
    lv_obj_set_height(ui_GoButton1, 60);
    lv_obj_set_x(ui_GoButton1, -160);
    lv_obj_set_y(ui_GoButton1, 100);
    lv_obj_set_align(ui_GoButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoButton1, lv_color_hex(0x00B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp4 = lv_label_create(ui_GoButton1);
    lv_obj_set_width(ui_Label10mmUp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp4, "持续\n挤出");
    lv_obj_set_style_text_align(ui_Label10mmUp4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoBackButton1, 50);
    lv_obj_set_height(ui_GoBackButton1, 60);
    lv_obj_set_x(ui_GoBackButton1, -90);
    lv_obj_set_y(ui_GoBackButton1, 100);
    lv_obj_set_align(ui_GoBackButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoBackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoBackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoBackButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoBackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp5 = lv_label_create(ui_GoBackButton1);
    lv_obj_set_width(ui_Label10mmUp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp5, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp5, "回抽");
    lv_obj_set_style_text_align(ui_Label10mmUp5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_StopButton1, 50);
    lv_obj_set_height(ui_StopButton1, 60);
    lv_obj_set_x(ui_StopButton1, -20);
    lv_obj_set_y(ui_StopButton1, 100);
    lv_obj_set_align(ui_StopButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopButton1, lv_color_hex(0xDE1C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp6 = lv_label_create(ui_StopButton1);
    lv_obj_set_width(ui_Label10mmUp6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp6, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp6, "停止");
    lv_obj_set_style_text_align(ui_Label10mmUp6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoButton2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoButton2, 50);
    lv_obj_set_height(ui_GoButton2, 60);
    lv_obj_set_x(ui_GoButton2, 70);
    lv_obj_set_y(ui_GoButton2, 100);
    lv_obj_set_align(ui_GoButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoButton2, lv_color_hex(0x00B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp7 = lv_label_create(ui_GoButton2);
    lv_obj_set_width(ui_Label10mmUp7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp7, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp7, "持续\n挤出");
    lv_obj_set_style_text_align(ui_Label10mmUp7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackButton2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoBackButton2, 50);
    lv_obj_set_height(ui_GoBackButton2, 60);
    lv_obj_set_x(ui_GoBackButton2, 135);
    lv_obj_set_y(ui_GoBackButton2, 100);
    lv_obj_set_align(ui_GoBackButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoBackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoBackButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoBackButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoBackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp8 = lv_label_create(ui_GoBackButton2);
    lv_obj_set_width(ui_Label10mmUp8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp8, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp8, "回抽");
    lv_obj_set_style_text_align(ui_Label10mmUp8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton5 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_StopButton5, 50);
    lv_obj_set_height(ui_StopButton5, 60);
    lv_obj_set_x(ui_StopButton5, 200);
    lv_obj_set_y(ui_StopButton5, 100);
    lv_obj_set_align(ui_StopButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopButton5, lv_color_hex(0xDE1C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp9 = lv_label_create(ui_StopButton5);
    lv_obj_set_width(ui_Label10mmUp9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp9, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp9, "停止");
    lv_obj_set_style_text_align(ui_Label10mmUp9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    //事件
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
    //设置温度
    lv_obj_add_event_cb(ui_SetTemp, ui_event_SetTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_T1Enter1, ui_event_T1Enter1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_T2Enter1, ui_event_T2Enter1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton1, ui_event_ApplyButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton2, ui_event_ApplyButton2, LV_EVENT_ALL, NULL);
    //纤维挤出
    lv_obj_add_event_cb(ui_GoButton1, ui_event_GoButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoBackButton1, ui_event_GoBackButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton1, ui_event_StopButton1, LV_EVENT_ALL, NULL);
    //树脂挤出
    lv_obj_add_event_cb(ui_GoButton2, ui_event_GoButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoBackButton2, ui_event_GoBackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton5, ui_event_StopButton5, LV_EVENT_ALL, NULL);
    //风扇
    lv_obj_add_event_cb(ui_Fan1Button2, ui_event_Fan1Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fan2Button2, ui_event_Fan2Button2, LV_EVENT_ALL, NULL);

}
