// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "../ui.h"

void ui_AxisScreen_screen_init(void)
{
    ui_AxisScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AxisScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AxisScreen, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AxisScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText1 = lv_label_create(ui_AxisScreen);
    lv_obj_set_width(ui_HeadText1, 215);
    lv_obj_set_height(ui_HeadText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText1, -90);
    lv_obj_set_y(ui_HeadText1, -150);
    lv_obj_set_align(ui_HeadText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText1, "纤维挤出头");
    lv_obj_set_style_text_align(ui_HeadText1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText2 = lv_label_create(ui_AxisScreen);
    lv_obj_set_width(ui_HeadText2, 215);
    lv_obj_set_height(ui_HeadText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText2, 130);
    lv_obj_set_y(ui_HeadText2, -150);
    lv_obj_set_align(ui_HeadText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText2, "树脂挤出头");
    lv_obj_set_style_text_align(ui_HeadText2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up1Button1 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up1Button1, 50);
    lv_obj_set_height(ui_Up1Button1, 70);
    lv_obj_set_x(ui_Up1Button1, -160);
    lv_obj_set_y(ui_Up1Button1, -95);
    lv_obj_set_align(ui_Up1Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up1Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up1Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up1Button1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up1Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1mmUp1 = lv_label_create(ui_Up1Button1);
    lv_obj_set_width(ui_Label1mmUp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1mmUp1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label1mmUp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1mmUp1, "上升\n1mm");
    lv_obj_set_style_text_align(ui_Label1mmUp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1mmUp1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up1Button2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up1Button2, 50);
    lv_obj_set_height(ui_Up1Button2, 70);
    lv_obj_set_x(ui_Up1Button2, -90);
    lv_obj_set_y(ui_Up1Button2, -95);
    lv_obj_set_align(ui_Up1Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up1Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up1Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up1Button2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up1Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5mmUp1 = lv_label_create(ui_Up1Button2);
    lv_obj_set_width(ui_Label5mmUp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5mmUp1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label5mmUp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5mmUp1, "上升\n5mm");
    lv_obj_set_style_text_align(ui_Label5mmUp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5mmUp1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up1Button3 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up1Button3, 50);
    lv_obj_set_height(ui_Up1Button3, 70);
    lv_obj_set_x(ui_Up1Button3, -20);
    lv_obj_set_y(ui_Up1Button3, -95);
    lv_obj_set_align(ui_Up1Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up1Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up1Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up1Button3, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up1Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp1 = lv_label_create(ui_Up1Button3);
    lv_obj_set_width(ui_Label10mmUp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp1, "上升\n10mm");
    lv_obj_set_style_text_align(ui_Label10mmUp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down1Button1 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down1Button1, 50);
    lv_obj_set_height(ui_Down1Button1, 70);
    lv_obj_set_x(ui_Down1Button1, -160);
    lv_obj_set_y(ui_Down1Button1, 20);
    lv_obj_set_align(ui_Down1Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down1Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down1Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down1Button1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down1Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1mmDown1 = lv_label_create(ui_Down1Button1);
    lv_obj_set_width(ui_Label1mmDown1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1mmDown1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label1mmDown1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1mmDown1, "下降\n1mm");
    lv_obj_set_style_text_align(ui_Label1mmDown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1mmDown1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down1Button2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down1Button2, 50);
    lv_obj_set_height(ui_Down1Button2, 70);
    lv_obj_set_x(ui_Down1Button2, -90);
    lv_obj_set_y(ui_Down1Button2, 20);
    lv_obj_set_align(ui_Down1Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down1Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down1Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down1Button2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down1Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5mmDown1 = lv_label_create(ui_Down1Button2);
    lv_obj_set_width(ui_Label5mmDown1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5mmDown1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label5mmDown1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5mmDown1, "下降\n5mm");
    lv_obj_set_style_text_align(ui_Label5mmDown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5mmDown1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down1Button3 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down1Button3, 50);
    lv_obj_set_height(ui_Down1Button3, 70);
    lv_obj_set_x(ui_Down1Button3, -20);
    lv_obj_set_y(ui_Down1Button3, 20);
    lv_obj_set_align(ui_Down1Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down1Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down1Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down1Button3, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down1Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmDown1 = lv_label_create(ui_Down1Button3);
    lv_obj_set_width(ui_Label10mmDown1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmDown1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmDown1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmDown1, "下降\n10mm");
    lv_obj_set_style_text_align(ui_Label10mmDown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmDown1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutButton = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutButton, 45);
    lv_obj_set_height(ui_CutButton, 70);
    lv_obj_set_x(ui_CutButton, 200);
    lv_obj_set_y(ui_CutButton, 110);
    lv_obj_set_align(ui_CutButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutButton, lv_color_hex(0xDBDD23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutLabel = lv_label_create(ui_CutButton);
    lv_obj_set_width(ui_CutLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CutLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutLabel, "剪切");
    lv_obj_set_style_text_color(ui_CutLabel, lv_color_hex(0xF70F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CutLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CutLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up2Button1 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up2Button1, 50);
    lv_obj_set_height(ui_Up2Button1, 70);
    lv_obj_set_x(ui_Up2Button1, 65);
    lv_obj_set_y(ui_Up2Button1, -95);
    lv_obj_set_align(ui_Up2Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up2Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up2Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up2Button1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up2Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1mmUp2 = lv_label_create(ui_Up2Button1);
    lv_obj_set_width(ui_Label1mmUp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1mmUp2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label1mmUp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1mmUp2, "上升\n1mm");
    lv_obj_set_style_text_align(ui_Label1mmUp2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1mmUp2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up2Button2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up2Button2, 50);
    lv_obj_set_height(ui_Up2Button2, 70);
    lv_obj_set_x(ui_Up2Button2, 130);
    lv_obj_set_y(ui_Up2Button2, -95);
    lv_obj_set_align(ui_Up2Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up2Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up2Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up2Button2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5mmUp2 = lv_label_create(ui_Up2Button2);
    lv_obj_set_width(ui_Label5mmUp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5mmUp2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label5mmUp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5mmUp2, "上升\n5mm");
    lv_obj_set_style_text_align(ui_Label5mmUp2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5mmUp2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up2Button3 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Up2Button3, 50);
    lv_obj_set_height(ui_Up2Button3, 70);
    lv_obj_set_x(ui_Up2Button3, 200);
    lv_obj_set_y(ui_Up2Button3, -95);
    lv_obj_set_align(ui_Up2Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up2Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Up2Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Up2Button3, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Up2Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp2 = lv_label_create(ui_Up2Button3);
    lv_obj_set_width(ui_Label10mmUp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp2, "上升\n10mm");
    lv_obj_set_style_text_align(ui_Label10mmUp2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down2Button1 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down2Button1, 50);
    lv_obj_set_height(ui_Down2Button1, 70);
    lv_obj_set_x(ui_Down2Button1, 60);
    lv_obj_set_y(ui_Down2Button1, 20);
    lv_obj_set_align(ui_Down2Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down2Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down2Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down2Button1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down2Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1mmDown2 = lv_label_create(ui_Down2Button1);
    lv_obj_set_width(ui_Label1mmDown2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1mmDown2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label1mmDown2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1mmDown2, "下降\n1mm");
    lv_obj_set_style_text_align(ui_Label1mmDown2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1mmDown2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down2Button2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down2Button2, 50);
    lv_obj_set_height(ui_Down2Button2, 70);
    lv_obj_set_x(ui_Down2Button2, 130);
    lv_obj_set_y(ui_Down2Button2, 20);
    lv_obj_set_align(ui_Down2Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down2Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down2Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down2Button2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5mmDown2 = lv_label_create(ui_Down2Button2);
    lv_obj_set_width(ui_Label5mmDown2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5mmDown2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label5mmDown2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5mmDown2, "下降\n5mm");
    lv_obj_set_style_text_align(ui_Label5mmDown2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5mmDown2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down2Button3 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Down2Button3, 50);
    lv_obj_set_height(ui_Down2Button3, 70);
    lv_obj_set_x(ui_Down2Button3, 200);
    lv_obj_set_y(ui_Down2Button3, 20);
    lv_obj_set_align(ui_Down2Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down2Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Down2Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Down2Button3, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Down2Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmDown2 = lv_label_create(ui_Down2Button3);
    lv_obj_set_width(ui_Label10mmDown2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmDown2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmDown2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmDown2, "下降\n10mm");
    lv_obj_set_style_text_align(ui_Label10mmDown2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmDown2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton1 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_ResetButton1, 80);
    lv_obj_set_height(ui_ResetButton1, 25);
    lv_obj_set_x(ui_ResetButton1, -125);
    lv_obj_set_y(ui_ResetButton1, -38);
    lv_obj_set_align(ui_ResetButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetButton1, lv_color_hex(0x01B30A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetText1 = lv_label_create(ui_ResetButton1);
    lv_obj_set_width(ui_ResetText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetText1, "复位");
    lv_obj_set_style_text_font(ui_ResetText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_ResetButton2, 80);
    lv_obj_set_height(ui_ResetButton2, 25);
    lv_obj_set_x(ui_ResetButton2, 95);
    lv_obj_set_y(ui_ResetButton2, -38);
    lv_obj_set_align(ui_ResetButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetButton2, lv_color_hex(0x01B30A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetText2 = lv_label_create(ui_ResetButton2);
    lv_obj_set_width(ui_ResetText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetText2, "复位");
    lv_obj_set_style_text_font(ui_ResetText2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterResetButton = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterResetButton, 40);
    lv_obj_set_height(ui_CutterResetButton, 80);
    lv_obj_set_x(ui_CutterResetButton, -160);
    lv_obj_set_y(ui_CutterResetButton, 110);
    lv_obj_set_align(ui_CutterResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterResetButton, lv_color_hex(0x00B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetCutter = lv_label_create(ui_CutterResetButton);
    lv_obj_set_width(ui_ResetCutter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetCutter, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_ResetCutter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetCutter, "复位\n剪刀");
    lv_obj_set_style_text_align(ui_ResetCutter, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetCutter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDownButton = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterDownButton, 40);
    lv_obj_set_height(ui_CutterDownButton, 55);
    lv_obj_set_x(ui_CutterDownButton, -105);
    lv_obj_set_y(ui_CutterDownButton, 110);
    lv_obj_set_align(ui_CutterDownButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterDownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterDownButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterDownButton, lv_color_hex(0xB40000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterDownButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDown = lv_label_create(ui_CutterDownButton);
    lv_obj_set_width(ui_CutterDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterDown, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_CutterDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterDown, "就位\n剪刀");
    lv_obj_set_style_text_align(ui_CutterDown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CutterDown, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterUp1mm = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterUp1mm, 80);
    lv_obj_set_height(ui_CutterUp1mm, 25);
    lv_obj_set_x(ui_CutterUp1mm, 30);
    lv_obj_set_y(ui_CutterUp1mm, 90);
    lv_obj_set_align(ui_CutterUp1mm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterUp1mm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterUp1mm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterUp1mm, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterUp1mm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterUp1mmLabel = lv_label_create(ui_CutterUp1mm);
    lv_obj_set_width(ui_CutterUp1mmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterUp1mmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CutterUp1mmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterUp1mmLabel, "上升 1mm");
    lv_obj_set_style_text_font(ui_CutterUp1mmLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterUp5mm = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterUp5mm, 80);
    lv_obj_set_height(ui_CutterUp5mm, 25);
    lv_obj_set_x(ui_CutterUp5mm, 120);
    lv_obj_set_y(ui_CutterUp5mm, 90);
    lv_obj_set_align(ui_CutterUp5mm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterUp5mm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterUp5mm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterUp5mm, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterUp5mm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterUp5mmLabel = lv_label_create(ui_CutterUp5mm);
    lv_obj_set_width(ui_CutterUp5mmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterUp5mmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CutterUp5mmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterUp5mmLabel, "上升 5mm");
    lv_obj_set_style_text_font(ui_CutterUp5mmLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDn1mm = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterDn1mm, 80);
    lv_obj_set_height(ui_CutterDn1mm, 25);
    lv_obj_set_x(ui_CutterDn1mm, 30);
    lv_obj_set_y(ui_CutterDn1mm, 130);
    lv_obj_set_align(ui_CutterDn1mm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterDn1mm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterDn1mm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterDn1mm, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterDn1mm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDn1mmLabel = lv_label_create(ui_CutterDn1mm);
    lv_obj_set_width(ui_CutterDn1mmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterDn1mmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CutterDn1mmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterDn1mmLabel, "下降 1mm");
    lv_obj_set_style_text_font(ui_CutterDn1mmLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDn5mm = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterDn5mm, 80);
    lv_obj_set_height(ui_CutterDn5mm, 25);
    lv_obj_set_x(ui_CutterDn5mm, 120);
    lv_obj_set_y(ui_CutterDn5mm, 130);
    lv_obj_set_align(ui_CutterDn5mm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterDn5mm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterDn5mm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterDn5mm, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterDn5mm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterDn5mmLabel = lv_label_create(ui_CutterDn5mm);
    lv_obj_set_width(ui_CutterDn5mmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterDn5mmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CutterDn5mmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterDn5mmLabel, "下降 5mm");
    lv_obj_set_style_text_font(ui_CutterDn5mmLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set1Button = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Set1Button, 55);
    lv_obj_set_height(ui_Set1Button, 25);
    lv_obj_set_x(ui_Set1Button, -40);
    lv_obj_set_y(ui_Set1Button, -38);
    lv_obj_set_align(ui_Set1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Set1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Set1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Set1Button, lv_color_hex(0xB30101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Set1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set1Text = lv_label_create(ui_Set1Button);
    lv_obj_set_width(ui_Set1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Set1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Set1Text, "就位");
    lv_obj_set_style_text_font(ui_Set1Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set2Button = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_Set2Button, 55);
    lv_obj_set_height(ui_Set2Button, 25);
    lv_obj_set_x(ui_Set2Button, 180);
    lv_obj_set_y(ui_Set2Button, -38);
    lv_obj_set_align(ui_Set2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Set2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Set2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Set2Button, lv_color_hex(0xB30101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Set2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set2Text = lv_label_create(ui_Set2Button);
    lv_obj_set_width(ui_Set2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Set2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Set2Text, "就位");
    lv_obj_set_style_text_font(ui_Set2Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton2 = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_HomeButton2, 40);
    lv_obj_set_height(ui_HomeButton2, 106);
    lv_obj_set_x(ui_HomeButton2, -220);
    lv_obj_set_y(ui_HomeButton2, -110);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton2, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLable2 = lv_label_create(ui_HomeButton2);
    lv_obj_set_width(ui_HomeLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLable2, 0);
    lv_obj_set_y(ui_HomeLable2, -15);
    lv_obj_set_align(ui_HomeLable2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLable2, "主页");
    lv_obj_set_style_text_color(ui_HomeLable2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLable2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLable2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage2 = lv_img_create(ui_HomeButton2);
    lv_img_set_src(ui_HomeImage2, &ui_img_home_fill_png);
    lv_obj_set_width(ui_HomeImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage2, 0);
    lv_obj_set_y(ui_HomeImage2, 10);
    lv_obj_set_align(ui_HomeImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HomeImage2, 30);

    ui_CutterStopButton = lv_btn_create(ui_AxisScreen);
    lv_obj_set_width(ui_CutterStopButton, 40);
    lv_obj_set_height(ui_CutterStopButton, 70);
    lv_obj_set_x(ui_CutterStopButton, -45);
    lv_obj_set_y(ui_CutterStopButton, 110);
    lv_obj_set_align(ui_CutterStopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CutterStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CutterStopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CutterStopButton, lv_color_hex(0x0172B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CutterStopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CutterStopText = lv_label_create(ui_CutterStopButton);
    lv_obj_set_width(ui_CutterStopText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CutterStopText, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_CutterStopText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CutterStopText, "停止\n剪刀");
    lv_obj_set_style_text_font(ui_CutterStopText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ResetButton1, ui_event_ResetButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton2, ui_event_ResetButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set1Button, ui_event_Set1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set2Button, ui_event_Set2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);

    //自定义事件
    lv_obj_add_event_cb(ui_CutterResetButton, ui_event_CutterResetButton,LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CutterDownButton, ui_event_CutterDownButton,LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CutterStopButton, ui_event_CutterStopButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up1Button1, ui_event_Up1Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up1Button2, ui_event_Up1Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up1Button3, ui_event_Up1Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down1Button1, ui_event_Down1Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down1Button2, ui_event_Down1Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down1Button3, ui_event_Down1Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up2Button1, ui_event_Up2Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up2Button2, ui_event_Up2Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up2Button3, ui_event_Up2Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down2Button1, ui_event_Down2Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down2Button2, ui_event_Down2Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Down2Button3, ui_event_Down2Button3, LV_EVENT_ALL, NULL);
}
