// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "../ui.h"

#include <stdio.h>

#include "fan.h"
#include "temperature.h"
#include "motor.h"

// UI 更新回调
static void update_ui_HomeScreen_per_second_cb(lv_timer_t *timer) 
{
    char buf[32]; 

    //纤维头温度
    float t1 = get_temperature1();
    snprintf(buf, sizeof(buf), "%.0f", t1);
    lv_label_set_text(ui_Extruder1Temp, buf);
    //纤维头位置
    float poisiton_X = get_X_position_mm();
    snprintf(buf, sizeof(buf), "%.0f", poisiton_X);
    lv_label_set_text(ui_PositonXText1, buf);
    //纤维头挤出速度
    float extrude_speed_1 = motor3_get_speed_mm_per_s();
    snprintf(buf, sizeof(buf), "%.0f", extrude_speed_1);
    lv_label_set_text(ui_Extruder1SpeedText1, buf);
    //纤维风扇状态
    bool is_fan1_on = fan_get_state(FAN1);
    if (is_fan1_on) {
        lv_label_set_text(ui_Extruder2Temp3, "ON");
    } else {
        lv_label_set_text(ui_Extruder2Temp3, "OFF");
    }


    //树脂头温度
    float t2 = get_temperature2();
    snprintf(buf, sizeof(buf), "%.0f", t2);
    lv_label_set_text(ui_Extruder2Temp, buf);
    //纤维头位置
    float poisiton_Y = get_Y_position_mm();
    snprintf(buf, sizeof(buf), "%.0f", poisiton_Y);
    lv_label_set_text(ui_PositonYText1, buf);
    //纤维头挤出速度
    float extrude_speed_2 = motor4_get_speed_mm_per_s();
    snprintf(buf, sizeof(buf), "%.0f", extrude_speed_2);
    lv_label_set_text(ui_Extruder2SpeedText1, buf);
    //树脂风扇状态
    bool is_fan2_on = fan_get_state(FAN2);
    if (is_fan2_on) {
        lv_label_set_text(ui_Extruder2Temp4, "ON");
    } else {
        lv_label_set_text(ui_Extruder2Temp4, "OFF");
    }
}

void ui_HomeScreen_screen_init(void)
{   
    lv_timer_create(update_ui_HomeScreen_per_second_cb, 1000, NULL);

    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonitorPanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_MonitorPanel, 200);
    lv_obj_set_height(ui_MonitorPanel, 290);
    lv_obj_set_x(ui_MonitorPanel, -110);
    lv_obj_set_y(ui_MonitorPanel, 0);
    lv_obj_set_align(ui_MonitorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MonitorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MonitorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MonitorPanel, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MonitorPanel, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MonitorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MonitorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder1, 180);
    lv_obj_set_height(ui_Extruder1, 30);
    lv_obj_set_x(ui_Extruder1, 0);
    lv_obj_set_y(ui_Extruder1, -130);
    lv_obj_set_align(ui_Extruder1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Text = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Extruder1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Text, -10);
    lv_obj_set_y(ui_Extruder1Text, 0);
    lv_obj_set_align(ui_Extruder1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Text, "纤维挤出头");
    lv_obj_set_style_text_align(ui_Extruder1Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Image = lv_img_create(ui_Extruder1);
    lv_img_set_src(ui_Extruder1Image, &ui_img_browser_extruder3_png);
    lv_obj_set_width(ui_Extruder1Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder1Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder1Image, -70);
    lv_obj_set_y(ui_Extruder1Image, 0);
    lv_obj_set_align(ui_Extruder1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder1Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder1Image, 20);

    ui_Extruder1Temp = lv_label_create(ui_Extruder1);
    lv_obj_set_width(ui_Extruder1Temp, 35);
    lv_obj_set_height(ui_Extruder1Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Temp, 60);
    lv_obj_set_y(ui_Extruder1Temp, 0);
    lv_obj_set_align(ui_Extruder1Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Temp, "T1");
    lv_obj_set_style_text_align(ui_Extruder1Temp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder2, 180);
    lv_obj_set_height(ui_Extruder2, 30);
    lv_obj_set_x(ui_Extruder2, 0);
    lv_obj_set_y(ui_Extruder2, 20);
    lv_obj_set_align(ui_Extruder2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Text = lv_label_create(ui_Extruder2);
    lv_obj_set_width(ui_Extruder2Text, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Extruder2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Text, -10);
    lv_obj_set_y(ui_Extruder2Text, 0);
    lv_obj_set_align(ui_Extruder2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Text, "树脂挤出头");
    lv_obj_set_style_text_align(ui_Extruder2Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Text, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Image = lv_img_create(ui_Extruder2);
    lv_img_set_src(ui_Extruder2Image, &ui_img_browser_extruder1_png);
    lv_obj_set_width(ui_Extruder2Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder2Image, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder2Image, -70);
    lv_obj_set_y(ui_Extruder2Image, 0);
    lv_obj_set_align(ui_Extruder2Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Extruder2Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder2Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder2Image, 20);

    ui_Extruder2Temp = lv_label_create(ui_Extruder2);
    lv_obj_set_width(ui_Extruder2Temp, 35);
    lv_obj_set_height(ui_Extruder2Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp, 60);
    lv_obj_set_y(ui_Extruder2Temp, 0);
    lv_obj_set_align(ui_Extruder2Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp, "T2");
    lv_obj_set_style_text_align(ui_Extruder2Temp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Fan1, 180);
    lv_obj_set_height(ui_Fan1, 30);
    lv_obj_set_x(ui_Fan1, 0);
    lv_obj_set_y(ui_Fan1, -60);
    lv_obj_set_align(ui_Fan1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Fan1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Fan1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Fan1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1Temp = lv_label_create(ui_Fan1);
    lv_obj_set_width(ui_Fan1Temp, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Fan1Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan1Temp, -10);
    lv_obj_set_y(ui_Fan1Temp, 0);
    lv_obj_set_align(ui_Fan1Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan1Temp, "纤维头风扇");
    lv_obj_set_style_text_align(ui_Fan1Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan1Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Temp3 = lv_label_create(ui_Fan1);
    lv_obj_set_width(ui_Extruder2Temp3, 35);
    lv_obj_set_height(ui_Extruder2Temp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp3, 60);
    lv_obj_set_y(ui_Extruder2Temp3, 0);
    lv_obj_set_align(ui_Extruder2Temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp3, "T4");
    lv_obj_set_style_text_align(ui_Extruder2Temp3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2 = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Fan2, 180);
    lv_obj_set_height(ui_Fan2, 30);
    lv_obj_set_x(ui_Fan2, 0);
    lv_obj_set_y(ui_Fan2, 90);
    lv_obj_set_align(ui_Fan2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Fan2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Fan2, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Fan2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2Temp = lv_label_create(ui_Fan2);
    lv_obj_set_width(ui_Fan2Temp, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Fan2Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan2Temp, -10);
    lv_obj_set_y(ui_Fan2Temp, 0);
    lv_obj_set_align(ui_Fan2Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan2Temp, "树脂头风扇");
    lv_obj_set_style_text_align(ui_Fan2Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan2Temp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Temp4 = lv_label_create(ui_Fan2);
    lv_obj_set_width(ui_Extruder2Temp4, 35);
    lv_obj_set_height(ui_Extruder2Temp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Temp4, 60);
    lv_obj_set_y(ui_Extruder2Temp4, 0);
    lv_obj_set_align(ui_Extruder2Temp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Temp4, "T5");
    lv_obj_set_style_text_align(ui_Extruder2Temp4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Temp4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositionX = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_PositionX, 180);
    lv_obj_set_height(ui_PositionX, 30);
    lv_obj_set_x(ui_PositionX, 0);
    lv_obj_set_y(ui_PositionX, -95);
    lv_obj_set_align(ui_PositionX, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PositionX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PositionX, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PositionX, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PositionX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositonXText = lv_label_create(ui_PositionX);
    lv_obj_set_width(ui_PositonXText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositonXText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositonXText, -10);
    lv_obj_set_y(ui_PositonXText, 0);
    lv_obj_set_align(ui_PositonXText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositonXText, "纤维头位置");
    lv_obj_set_style_text_align(ui_PositonXText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositonXText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositonXText1 = lv_label_create(ui_PositionX);
    lv_obj_set_width(ui_PositonXText1, 35);
    lv_obj_set_height(ui_PositonXText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositonXText1, 60);
    lv_obj_set_y(ui_PositonXText1, 0);
    lv_obj_set_align(ui_PositonXText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositonXText1, "X");
    lv_obj_set_style_text_align(ui_PositonXText1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositonXText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositionY = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_PositionY, 180);
    lv_obj_set_height(ui_PositionY, 30);
    lv_obj_set_x(ui_PositionY, 0);
    lv_obj_set_y(ui_PositionY, 55);
    lv_obj_set_align(ui_PositionY, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PositionY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PositionY, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PositionY, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PositionY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositonYText = lv_label_create(ui_PositionY);
    lv_obj_set_width(ui_PositonYText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositonYText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositonYText, -10);
    lv_obj_set_y(ui_PositonYText, 0);
    lv_obj_set_align(ui_PositonYText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositonYText, "树脂头位置");
    lv_obj_set_style_text_align(ui_PositonYText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositonYText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositonYText1 = lv_label_create(ui_PositionY);
    lv_obj_set_width(ui_PositonYText1, 35);
    lv_obj_set_height(ui_PositonYText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositonYText1, 60);
    lv_obj_set_y(ui_PositonYText1, 0);
    lv_obj_set_align(ui_PositonYText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositonYText1, "Y");
    lv_obj_set_style_text_align(ui_PositonYText1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositonYText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Speed = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder1Speed, 180);
    lv_obj_set_height(ui_Extruder1Speed, 30);
    lv_obj_set_x(ui_Extruder1Speed, 0);
    lv_obj_set_y(ui_Extruder1Speed, -25);
    lv_obj_set_align(ui_Extruder1Speed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder1Speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder1Speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder1Speed, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder1Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder1Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1SpeedText = lv_label_create(ui_Extruder1Speed);
    lv_obj_set_width(ui_Extruder1SpeedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder1SpeedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1SpeedText, -10);
    lv_obj_set_y(ui_Extruder1SpeedText, 0);
    lv_obj_set_align(ui_Extruder1SpeedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1SpeedText, "纤维头挤出");
    lv_obj_set_style_text_align(ui_Extruder1SpeedText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1SpeedText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1SpeedText1 = lv_label_create(ui_Extruder1Speed);
    lv_obj_set_width(ui_Extruder1SpeedText1, 35);
    lv_obj_set_height(ui_Extruder1SpeedText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1SpeedText1, 60);
    lv_obj_set_y(ui_Extruder1SpeedText1, 0);
    lv_obj_set_align(ui_Extruder1SpeedText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1SpeedText1, "V1");
    lv_obj_set_style_text_align(ui_Extruder1SpeedText1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1SpeedText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Speed = lv_obj_create(ui_MonitorPanel);
    lv_obj_set_width(ui_Extruder2Speed, 180);
    lv_obj_set_height(ui_Extruder2Speed, 30);
    lv_obj_set_x(ui_Extruder2Speed, 0);
    lv_obj_set_y(ui_Extruder2Speed, 125);
    lv_obj_set_align(ui_Extruder2Speed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder2Speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder2Speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder2Speed, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder2Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder2Speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2SpeedText = lv_label_create(ui_Extruder2Speed);
    lv_obj_set_width(ui_Extruder2SpeedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder2SpeedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2SpeedText, -10);
    lv_obj_set_y(ui_Extruder2SpeedText, 0);
    lv_obj_set_align(ui_Extruder2SpeedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2SpeedText, "纤维头挤出");
    lv_obj_set_style_text_align(ui_Extruder2SpeedText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2SpeedText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2SpeedText1 = lv_label_create(ui_Extruder2Speed);
    lv_obj_set_width(ui_Extruder2SpeedText1, 35);
    lv_obj_set_height(ui_Extruder2SpeedText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2SpeedText1, 60);
    lv_obj_set_y(ui_Extruder2SpeedText1, 0);
    lv_obj_set_align(ui_Extruder2SpeedText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2SpeedText1, "V2");
    lv_obj_set_style_text_align(ui_Extruder2SpeedText1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2SpeedText1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AxisButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_AxisButton, 90);
    lv_obj_set_height(ui_AxisButton, 90);
    lv_obj_set_x(ui_AxisButton, 75);
    lv_obj_set_y(ui_AxisButton, -100);
    lv_obj_set_align(ui_AxisButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AxisButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AxisButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AxisButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AxisButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AxisButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AxisButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AxisButton, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AxisLable = lv_label_create(ui_AxisButton);
    lv_obj_set_width(ui_AxisLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AxisLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AxisLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AxisLable, "位置校准");
    lv_obj_set_style_text_font(ui_AxisLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_TempButton, 90);
    lv_obj_set_height(ui_TempButton, 90);
    lv_obj_set_x(ui_TempButton, 175);
    lv_obj_set_y(ui_TempButton, -100);
    lv_obj_set_align(ui_TempButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempButton, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLable = lv_label_create(ui_TempButton);
    lv_obj_set_width(ui_TempLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLable, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_TempLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLable, "温度与挤出");
    lv_obj_set_style_text_align(ui_TempLable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_CalibrationButton, 90);
    lv_obj_set_height(ui_CalibrationButton, 90);
    lv_obj_set_x(ui_CalibrationButton, 75);
    lv_obj_set_y(ui_CalibrationButton, 0);
    lv_obj_set_align(ui_CalibrationButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalibrationButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibrationButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibrationButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CalibrationButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationLable = lv_label_create(ui_CalibrationButton);
    lv_obj_set_width(ui_CalibrationLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationLable, "初始化");
    lv_obj_set_style_text_font(ui_CalibrationLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_SettingButton, 90);
    lv_obj_set_height(ui_SettingButton, 90);
    lv_obj_set_x(ui_SettingButton, 175);
    lv_obj_set_y(ui_SettingButton, 0);
    lv_obj_set_align(ui_SettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingButton, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingLable = lv_label_create(ui_SettingButton);
    lv_obj_set_width(ui_SettingLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingLable, "通信设置");
    lv_obj_set_style_text_font(ui_SettingLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AxisButton, ui_event_AxisButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempButton, ui_event_TempButton, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_CalibrationButton, ui_event_CalibrationButton, LV_EVENT_ALL, NULL); //初始化


}
