// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "../ui.h"

#include <stdio.h>
#include <stdlib.h> 
#include <string.h>

#include "fan.h"
#include "temperature.h"
#include "motor.h"

// UI 更新回调
static void update_ui_TempScreen_per_second_cb(lv_timer_t *timer) 
{
    char buf[64]; 

    //纤维头温度、挤出速度、回抽速度
    float t1 = get_temperature1();
    float extrude_speed_1 = motor3_get_speed_mm_per_s();
    float retract_speed_1 = motor3_get_retract_speed_mm_per_s(); 

    snprintf(buf, sizeof(buf),
             "温度: %.0f \n\n"
             "速度: %.2f mm/s\n\n"
             "回抽: %.2f mm/s",
             t1, extrude_speed_1, retract_speed_1);

    lv_label_set_text(ui_Extruder1Status, buf);

    //树脂头温度、挤出速度、回抽速度
    float t2 = get_temperature2();
    float extrude_speed_2 = motor4_get_speed_mm_per_s();
    float retract_speed_2 = motor4_get_retract_speed_mm_per_s(); 
    snprintf(buf, sizeof(buf),
             "温度: %.0f \n\n"
             "速度: %.2f mm/s\n\n"
             "回抽: %.2f mm/s",
             t2, extrude_speed_2, retract_speed_2);

    lv_label_set_text(ui_Extruder2Status, buf);
    
}

void ui_TempScreen_screen_init(void)
{   
    lv_timer_create(update_ui_TempScreen_per_second_cb, 1000, NULL);//温度+速度状态更新

    ui_TempScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TempScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempScreen, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTemp = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_SetTemp, 115);
    lv_obj_set_height(ui_SetTemp, 40);
    lv_obj_set_x(ui_SetTemp, 21);
    lv_obj_set_y(ui_SetTemp, 25);
    lv_obj_set_align(ui_SetTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTempText = lv_label_create(ui_SetTemp);
    lv_obj_set_width(ui_SetTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTempText, "设定挤出参数");
    lv_obj_set_style_text_align(ui_SetTempText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTempText, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetExtruderTempPanel = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_SetExtruderTempPanel, 400);
    lv_obj_set_height(ui_SetExtruderTempPanel, 290);
    lv_obj_set_x(ui_SetExtruderTempPanel, 20);
    lv_obj_set_y(ui_SetExtruderTempPanel, -10);
    lv_obj_set_align(ui_SetExtruderTempPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetExtruderTempPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SetExtruderTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetExtruderTempPanel, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetExtruderTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetExtruderTempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetExtruderTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetExtruderTempPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_SetExtruderTempPanel);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 250);
    lv_obj_set_height(ui_Keyboard1, 130);
    lv_obj_set_x(ui_Keyboard1, -60);
    lv_obj_set_y(ui_Keyboard1, 73);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Keyboard1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Keyboard1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_T1Enter1 = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_T1Enter1, 120);
    lv_obj_set_height(ui_T1Enter1, 40);
    lv_obj_set_x(ui_T1Enter1, -120);
    lv_obj_set_y(ui_T1Enter1, -115);
    lv_obj_set_align(ui_T1Enter1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_T1Enter1, "纤维加热温度");
    lv_obj_set_style_text_font(ui_T1Enter1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_T1Enter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_T1Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_T1Enter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_T1Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_T2Enter1 = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_T2Enter1, 120);
    lv_obj_set_height(ui_T2Enter1, 40);
    lv_obj_set_x(ui_T2Enter1, 70);
    lv_obj_set_y(ui_T2Enter1, -115);
    lv_obj_set_align(ui_T2Enter1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_T2Enter1, "树脂加热温度");
    lv_obj_set_style_text_font(ui_T2Enter1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_T2Enter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_T2Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_T2Enter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_T2Enter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ApplyButton1 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton1, 50);
    lv_obj_set_height(ui_ApplyButton1, 20);
    lv_obj_set_x(ui_ApplyButton1, -35);
    lv_obj_set_y(ui_ApplyButton1, -115);
    lv_obj_set_align(ui_ApplyButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT1 = lv_label_create(ui_ApplyButton1);
    lv_obj_set_width(ui_LabelApplyT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT1, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ApplyButton2 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton2, 50);
    lv_obj_set_height(ui_ApplyButton2, 20);
    lv_obj_set_x(ui_ApplyButton2, 155);
    lv_obj_set_y(ui_ApplyButton2, -115);
    lv_obj_set_align(ui_ApplyButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT2 = lv_label_create(ui_ApplyButton2);
    lv_obj_set_width(ui_LabelApplyT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT2, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_BackButton, 65);
    lv_obj_set_height(ui_BackButton, 23);
    lv_obj_set_x(ui_BackButton, 154);
    lv_obj_set_y(ui_BackButton, 74);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x202123), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBack = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_LabelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack, "返回");
    lv_obj_set_style_text_color(ui_LabelBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_V1Enter = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_V1Enter, 120);
    lv_obj_set_height(ui_V1Enter, 40);
    lv_obj_set_x(ui_V1Enter, -120);
    lv_obj_set_y(ui_V1Enter, -65);
    lv_obj_set_align(ui_V1Enter, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_V1Enter, "纤维挤出速度");
    lv_obj_set_style_text_font(ui_V1Enter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_V1Enter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_V1Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_V1Enter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_V1Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_V2Enter = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_V2Enter, 120);
    lv_obj_set_height(ui_V2Enter, 40);
    lv_obj_set_x(ui_V2Enter, 70);
    lv_obj_set_y(ui_V2Enter, -65);
    lv_obj_set_align(ui_V2Enter, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_V2Enter, "树脂挤出速度");
    lv_obj_set_style_text_font(ui_V2Enter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_V2Enter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_V2Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_V2Enter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_V2Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ApplyButton4 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton4, 50);
    lv_obj_set_height(ui_ApplyButton4, 20);
    lv_obj_set_x(ui_ApplyButton4, 155);
    lv_obj_set_y(ui_ApplyButton4, -65);
    lv_obj_set_align(ui_ApplyButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT4 = lv_label_create(ui_ApplyButton4);
    lv_obj_set_width(ui_LabelApplyT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT4, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ApplyButton3 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton3, 50);
    lv_obj_set_height(ui_ApplyButton3, 20);
    lv_obj_set_x(ui_ApplyButton3, -35);
    lv_obj_set_y(ui_ApplyButton3, -65);
    lv_obj_set_align(ui_ApplyButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT3 = lv_label_create(ui_ApplyButton3);
    lv_obj_set_width(ui_LabelApplyT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT3, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vb1Enter = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_Vb1Enter, 120);
    lv_obj_set_height(ui_Vb1Enter, 40);
    lv_obj_set_x(ui_Vb1Enter, -120);
    lv_obj_set_y(ui_Vb1Enter, -15);
    lv_obj_set_align(ui_Vb1Enter, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Vb1Enter, "纤维回抽速度");
    lv_obj_set_style_text_font(ui_Vb1Enter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Vb1Enter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Vb1Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Vb1Enter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Vb1Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ApplyButton5 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton5, 50);
    lv_obj_set_height(ui_ApplyButton5, 20);
    lv_obj_set_x(ui_ApplyButton5, -35);
    lv_obj_set_y(ui_ApplyButton5, -15);
    lv_obj_set_align(ui_ApplyButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT5 = lv_label_create(ui_ApplyButton5);
    lv_obj_set_width(ui_LabelApplyT5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT5, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vb2Enter = lv_textarea_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_Vb2Enter, 120);
    lv_obj_set_height(ui_Vb2Enter, 40);
    lv_obj_set_x(ui_Vb2Enter, 70);
    lv_obj_set_y(ui_Vb2Enter, -15);
    lv_obj_set_align(ui_Vb2Enter, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Vb2Enter, "树脂回抽速度");
    lv_obj_set_style_text_font(ui_Vb2Enter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Vb2Enter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Vb2Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Vb2Enter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Vb2Enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ApplyButton6 = lv_btn_create(ui_SetExtruderTempPanel);
    lv_obj_set_width(ui_ApplyButton6, 50);
    lv_obj_set_height(ui_ApplyButton6, 20);
    lv_obj_set_x(ui_ApplyButton6, 155);
    lv_obj_set_y(ui_ApplyButton6, -15);
    lv_obj_set_align(ui_ApplyButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ApplyButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ApplyButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ApplyButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ApplyButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplyT6 = lv_label_create(ui_ApplyButton6);
    lv_obj_set_width(ui_LabelApplyT6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplyT6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelApplyT6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplyT6, "确认");
    lv_obj_set_style_text_color(ui_LabelApplyT6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplyT6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplyT6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1Button2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_Fan1Button2, 80);
    lv_obj_set_height(ui_Fan1Button2, 40);
    lv_obj_set_x(ui_Fan1Button2, -100);
    lv_obj_set_y(ui_Fan1Button2, 25);
    lv_obj_set_align(ui_Fan1Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan1Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fan1Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fan1Button2, lv_color_hex(0x520404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan1Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan1OFLabel2 = lv_label_create(ui_Fan1Button2);
    lv_obj_set_width(ui_Fan1OFLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan1OFLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fan1OFLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan1OFLabel2, "纤维风扇\n开/关");
    lv_obj_set_style_text_align(ui_Fan1OFLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan1OFLabel2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2Button2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_Fan2Button2, 80);
    lv_obj_set_height(ui_Fan2Button2, 40);
    lv_obj_set_x(ui_Fan2Button2, 150);
    lv_obj_set_y(ui_Fan2Button2, 25);
    lv_obj_set_align(ui_Fan2Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fan2Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fan2Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fan2Button2, lv_color_hex(0x520400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2OFLabel3 = lv_label_create(ui_Fan2Button2);
    lv_obj_set_width(ui_Fan2OFLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan2OFLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fan2OFLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan2OFLabel3, "树脂风扇\n开/关");
    lv_obj_set_style_text_align(ui_Fan2OFLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan2OFLabel3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton3 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_HomeButton3, 40);
    lv_obj_set_height(ui_HomeButton3, 106);
    lv_obj_set_x(ui_HomeButton3, -220);
    lv_obj_set_y(ui_HomeButton3, -110);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0x444244), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLable3 = lv_label_create(ui_HomeButton3);
    lv_obj_set_width(ui_HomeLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLable3, 0);
    lv_obj_set_y(ui_HomeLable3, -15);
    lv_obj_set_align(ui_HomeLable3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLable3, "主页");
    lv_obj_set_style_text_color(ui_HomeLable3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLable3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLable3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeImage3 = lv_img_create(ui_HomeButton3);
    lv_img_set_src(ui_HomeImage3, &ui_img_home_fill_png);
    lv_obj_set_width(ui_HomeImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeImage3, 0);
    lv_obj_set_y(ui_HomeImage3, 10);
    lv_obj_set_align(ui_HomeImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HomeImage3, 30);

    ui_Extruder4 = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_Extruder4, 200);
    lv_obj_set_height(ui_Extruder4, 130);
    lv_obj_set_x(ui_Extruder4, -85);
    lv_obj_set_y(ui_Extruder4, -80);
    lv_obj_set_align(ui_Extruder4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder4, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Text2 = lv_label_create(ui_Extruder4);
    lv_obj_set_width(ui_Extruder1Text2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Extruder1Text2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder1Text2, 0);
    lv_obj_set_y(ui_Extruder1Text2, -50);
    lv_obj_set_align(ui_Extruder1Text2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Text2, "纤维挤出头");
    lv_obj_set_style_text_align(ui_Extruder1Text2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Text2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder1Image2 = lv_img_create(ui_Extruder4);
    lv_img_set_src(ui_Extruder1Image2, &ui_img_browser_extruder3_png);
    lv_obj_set_width(ui_Extruder1Image2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder1Image2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder1Image2, -80);
    lv_obj_set_y(ui_Extruder1Image2, -100);
    lv_obj_set_align(ui_Extruder1Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Extruder1Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder1Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder1Image2, 20);

    ui_Extruder1Status = lv_label_create(ui_Extruder4);
    lv_obj_set_width(ui_Extruder1Status, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Extruder1Status, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Extruder1Status, -25);
    lv_obj_set_y(ui_Extruder1Status, 10);
    lv_obj_set_align(ui_Extruder1Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder1Status, "温度:XX\n\n速度:XX\n\n回抽:XX");
    lv_obj_set_style_text_align(ui_Extruder1Status, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder1Status, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder5 = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_Extruder5, 200);
    lv_obj_set_height(ui_Extruder5, 130);
    lv_obj_set_x(ui_Extruder5, 130);
    lv_obj_set_y(ui_Extruder5, -80);
    lv_obj_set_align(ui_Extruder5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Extruder5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Extruder5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Extruder5, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Extruder5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Extruder5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Text2 = lv_label_create(ui_Extruder5);
    lv_obj_set_width(ui_Extruder2Text2, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Extruder2Text2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Extruder2Text2, 0);
    lv_obj_set_y(ui_Extruder2Text2, -50);
    lv_obj_set_align(ui_Extruder2Text2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Text2, "树脂挤出头");
    lv_obj_set_style_text_align(ui_Extruder2Text2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Text2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Extruder2Image2 = lv_img_create(ui_Extruder5);
    lv_img_set_src(ui_Extruder2Image2, &ui_img_browser_extruder1_png);
    lv_obj_set_width(ui_Extruder2Image2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Extruder2Image2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Extruder2Image2, -80);
    lv_obj_set_y(ui_Extruder2Image2, -100);
    lv_obj_set_align(ui_Extruder2Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Extruder2Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Extruder2Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Extruder2Image2, 20);

    ui_Extruder2Status = lv_label_create(ui_Extruder5);
    lv_obj_set_width(ui_Extruder2Status, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Extruder2Status, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Extruder2Status, -25);
    lv_obj_set_y(ui_Extruder2Status, 10);
    lv_obj_set_align(ui_Extruder2Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Extruder2Status, "温度:XX\n\n速度:XX\n\n回抽:XX");
    lv_obj_set_style_text_align(ui_Extruder2Status, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Extruder2Status, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText4 = lv_label_create(ui_TempScreen);
    lv_obj_set_width(ui_HeadText4, 215);
    lv_obj_set_height(ui_HeadText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText4, -90);
    lv_obj_set_y(ui_HeadText4, 150);
    lv_obj_set_align(ui_HeadText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText4, "纤维挤出头");
    lv_obj_set_style_text_align(ui_HeadText4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText4, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadText5 = lv_label_create(ui_TempScreen);
    lv_obj_set_width(ui_HeadText5, 215);
    lv_obj_set_height(ui_HeadText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadText5, 130);
    lv_obj_set_y(ui_HeadText5, 150);
    lv_obj_set_align(ui_HeadText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeadText5, "树脂挤出头");
    lv_obj_set_style_text_align(ui_HeadText5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeadText5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeadText5, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoButton1, 50);
    lv_obj_set_height(ui_GoButton1, 60);
    lv_obj_set_x(ui_GoButton1, -160);
    lv_obj_set_y(ui_GoButton1, 100);
    lv_obj_set_align(ui_GoButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoButton1, lv_color_hex(0x00B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp4 = lv_label_create(ui_GoButton1);
    lv_obj_set_width(ui_Label10mmUp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp4, "挤出");
    lv_obj_set_style_text_align(ui_Label10mmUp4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoBackButton1, 50);
    lv_obj_set_height(ui_GoBackButton1, 60);
    lv_obj_set_x(ui_GoBackButton1, -90);
    lv_obj_set_y(ui_GoBackButton1, 100);
    lv_obj_set_align(ui_GoBackButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoBackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoBackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoBackButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoBackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp5 = lv_label_create(ui_GoBackButton1);
    lv_obj_set_width(ui_Label10mmUp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp5, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp5, "回抽");
    lv_obj_set_style_text_align(ui_Label10mmUp5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton1 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_StopButton1, 50);
    lv_obj_set_height(ui_StopButton1, 60);
    lv_obj_set_x(ui_StopButton1, -20);
    lv_obj_set_y(ui_StopButton1, 100);
    lv_obj_set_align(ui_StopButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopButton1, lv_color_hex(0xDE1C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp6 = lv_label_create(ui_StopButton1);
    lv_obj_set_width(ui_Label10mmUp6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp6, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp6, "停止");
    lv_obj_set_style_text_align(ui_Label10mmUp6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoButton2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoButton2, 50);
    lv_obj_set_height(ui_GoButton2, 60);
    lv_obj_set_x(ui_GoButton2, 70);
    lv_obj_set_y(ui_GoButton2, 100);
    lv_obj_set_align(ui_GoButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoButton2, lv_color_hex(0x00B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp7 = lv_label_create(ui_GoButton2);
    lv_obj_set_width(ui_Label10mmUp7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp7, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp7, "挤出");
    lv_obj_set_style_text_align(ui_Label10mmUp7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackButton2 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_GoBackButton2, 50);
    lv_obj_set_height(ui_GoBackButton2, 60);
    lv_obj_set_x(ui_GoBackButton2, 135);
    lv_obj_set_y(ui_GoBackButton2, 100);
    lv_obj_set_align(ui_GoBackButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoBackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GoBackButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GoBackButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GoBackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp8 = lv_label_create(ui_GoBackButton2);
    lv_obj_set_width(ui_Label10mmUp8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp8, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp8, "回抽");
    lv_obj_set_style_text_align(ui_Label10mmUp8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton5 = lv_btn_create(ui_TempScreen);
    lv_obj_set_width(ui_StopButton5, 50);
    lv_obj_set_height(ui_StopButton5, 60);
    lv_obj_set_x(ui_StopButton5, 200);
    lv_obj_set_y(ui_StopButton5, 100);
    lv_obj_set_align(ui_StopButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopButton5, lv_color_hex(0xDE1C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10mmUp9 = lv_label_create(ui_StopButton5);
    lv_obj_set_width(ui_Label10mmUp9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10mmUp9, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label10mmUp9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10mmUp9, "停止");
    lv_obj_set_style_text_align(ui_Label10mmUp9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10mmUp9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SetTemp, ui_event_SetTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_T1Enter1, ui_event_T1Enter1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_T2Enter1, ui_event_T2Enter1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_V1Enter, ui_event_V1Enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_V2Enter, ui_event_V2Enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Vb1Enter, ui_event_Vb1Enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Vb2Enter, ui_event_Vb2Enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton1, ui_event_ApplyButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton2, ui_event_ApplyButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton3, ui_event_ApplyButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton4, ui_event_ApplyButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton5, ui_event_ApplyButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ApplyButton6, ui_event_ApplyButton6, LV_EVENT_ALL, NULL);

    //纤维挤出
    lv_obj_add_event_cb(ui_GoButton1, ui_event_GoButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoBackButton1, ui_event_GoBackButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton1, ui_event_StopButton1, LV_EVENT_ALL, NULL);
    //树脂挤出
    lv_obj_add_event_cb(ui_GoButton2, ui_event_GoButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoBackButton2, ui_event_GoBackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton5, ui_event_StopButton5, LV_EVENT_ALL, NULL);
    //风扇
    lv_obj_add_event_cb(ui_Fan1Button2, ui_event_Fan1Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fan2Button2, ui_event_Fan2Button2, LV_EVENT_ALL, NULL);

}
