// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 320x240

#include "ui.h"
#include "ui_helpers.h"


#include "esp_log.h"
#include "motor.h"
#include "pid_ctrl.h"
#include "cutter.h"
#include "fan.h"
#include "temperature.h"

///////////////////// VARIABLES声明 ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
void ui_event_HomeButton(lv_event_t * e);
lv_obj_t * ui_HomeButton;
lv_obj_t * ui_HomeLable;
lv_obj_t * ui_HomeImage;
lv_obj_t * ui_PowerButton;
lv_obj_t * ui_StopButton;
lv_obj_t * ui_StopLable;
lv_obj_t * ui_StopImage;
lv_obj_t * ui_ProcessPanel;
lv_obj_t * ui_FileName;
lv_obj_t * ui_StartTime;
lv_obj_t * ui_Progress;
lv_obj_t * ui_FileNameText;
lv_obj_t * ui_StartTimeText;
lv_obj_t * ui_ProgressText;
lv_obj_t * ui_MonitorPanel;
lv_obj_t * ui_Extruder1;
lv_obj_t * ui_Extruder1Text;
lv_obj_t * ui_Extruder1Image;
lv_obj_t * ui_Extruder1Temp;
lv_obj_t * ui_Extruder2;
lv_obj_t * ui_Extruder2Text;
lv_obj_t * ui_Extruder2Image;
lv_obj_t * ui_Extruder2Temp;
lv_obj_t * ui_Fan1;
lv_obj_t * ui_Fan1Temp;
lv_obj_t * ui_Fan1Image;
lv_obj_t * ui_Extruder2Temp3;
lv_obj_t * ui_Fan2;
lv_obj_t * ui_Fan2Temp;
lv_obj_t * ui_Fan2Image;
lv_obj_t * ui_Extruder2Temp4;
void ui_event_AxisButton(lv_event_t * e);
lv_obj_t * ui_AxisButton;
lv_obj_t * ui_AxisLable;
void ui_event_TempButton(lv_event_t * e);
lv_obj_t * ui_TempButton;
lv_obj_t * ui_TempLable;
lv_obj_t * ui_CalibrationButton;
lv_obj_t * ui_CalibrationLable;
lv_obj_t * ui_SettingButton;
lv_obj_t * ui_SettingLable;
lv_obj_t * ui_StartButton;
lv_obj_t * ui_StartLable;
// CUSTOM VARIABLES


// SCREEN: ui_AxisScreen
void ui_AxisScreen_screen_init(void);
lv_obj_t * ui_AxisScreen;
lv_obj_t * ui_HeadText1;
lv_obj_t * ui_HeadText2;
lv_obj_t * ui_Up1Button1;
lv_obj_t * ui_Label1mmUp1;
lv_obj_t * ui_Up1Button2;
lv_obj_t * ui_Label5mmUp1;
lv_obj_t * ui_Up1Button3;
lv_obj_t * ui_Label10mmUp1;
lv_obj_t * ui_Down1Button1;
lv_obj_t * ui_Label1mmDown1;
lv_obj_t * ui_Down1Button2;
lv_obj_t * ui_Label5mmDown1;
lv_obj_t * ui_Down1Button3;
lv_obj_t * ui_Label10mmDown1;
lv_obj_t * ui_CutButton;
lv_obj_t * ui_CutLabel;
lv_obj_t * ui_Up2Button1;
lv_obj_t * ui_Label1mmUp2;
lv_obj_t * ui_Up2Button2;
lv_obj_t * ui_Label5mmUp2;
lv_obj_t * ui_Up2Button3;
lv_obj_t * ui_Label10mmUp2;
lv_obj_t * ui_Down2Button1;
lv_obj_t * ui_Label1mmDown2;
lv_obj_t * ui_Down2Button2;
lv_obj_t * ui_Label5mmDown2;
lv_obj_t * ui_Down2Button3;
lv_obj_t * ui_Label10mmDown2;
void ui_event_ResetButton1(lv_event_t * e);
lv_obj_t * ui_ResetButton1;
lv_obj_t * ui_ResetText1;
void ui_event_ResetButton2(lv_event_t * e);
lv_obj_t * ui_ResetButton2;
lv_obj_t * ui_ResetText2;
lv_obj_t * ui_CutterResetButton;
lv_obj_t * ui_ResetCutter;
lv_obj_t * ui_CutterDownButton;
lv_obj_t * ui_CutterDown;
lv_obj_t * ui_CutterUp1mm;
lv_obj_t * ui_CutterUp1mmLabel;
lv_obj_t * ui_CutterUp5mm;
lv_obj_t * ui_CutterUp5mmLabel;
lv_obj_t * ui_CutterDn1mm;
lv_obj_t * ui_CutterDn1mmLabel;
lv_obj_t * ui_CutterDn5mm;
lv_obj_t * ui_CutterDn5mmLabel;
void ui_event_Set1Button(lv_event_t * e);
lv_obj_t * ui_Set1Button;
lv_obj_t * ui_Set1Text;
void ui_event_Set2Button(lv_event_t * e);
lv_obj_t * ui_Set2Button;
lv_obj_t * ui_Set2Text;
void ui_event_HomeButton2(lv_event_t * e);
lv_obj_t * ui_HomeButton2;
lv_obj_t * ui_HomeLable2;
lv_obj_t * ui_HomeImage2;
lv_obj_t * ui_StopButton2;
lv_obj_t * ui_StopLable2;
lv_obj_t * ui_StopImage2;
lv_obj_t * ui_PowerButton2;
lv_obj_t * ui_CutterStopButton;
lv_obj_t * ui_CutterStopText;
// CUSTOM VARIABLES

//剪刀事件
void ui_event_CutterStopButton(lv_event_t * e);
void ui_event_CutterResetButton(lv_event_t * e);
void ui_event_CutterDownButton(lv_event_t * e);
//纤维轴事件
void ui_event_Up1Button1(lv_event_t * e);
void ui_event_Up1Button2(lv_event_t * e);
void ui_event_Up1Button3(lv_event_t * e);
void ui_event_Down1Button1(lv_event_t * e);
void ui_event_Down1Button2(lv_event_t * e);
void ui_event_Down1Button3(lv_event_t * e);
//树脂轴事件
void ui_event_Up2Button1(lv_event_t * e);
void ui_event_Up2Button2(lv_event_t * e);
void ui_event_Up2Button3(lv_event_t * e);
void ui_event_Down2Button1(lv_event_t * e);
void ui_event_Down2Button2(lv_event_t * e);
void ui_event_Down2Button3(lv_event_t * e);

// SCREEN: ui_TempScreen
void ui_TempScreen_screen_init(void);
lv_obj_t * ui_TempScreen;
void ui_event_SetTemp(lv_event_t * e);
lv_obj_t * ui_SetTemp;
lv_obj_t * ui_SetTempText;
lv_obj_t * ui_SetExtruderTempPanel;
lv_obj_t * ui_Keyboard1;
void ui_event_T1Enter1(lv_event_t * e);
lv_obj_t * ui_T1Enter1;
void ui_event_T2Enter1(lv_event_t * e);
lv_obj_t * ui_T2Enter1;
lv_obj_t * ui_ApplyButton1;
lv_obj_t * ui_LabelApplyT1;
lv_obj_t * ui_ApplyButton2;
lv_obj_t * ui_LabelApplyT2;
void ui_event_BackButton(lv_event_t * e);
lv_obj_t * ui_BackButton;
lv_obj_t * ui_LabelBack;
lv_obj_t * ui_Fan1Button2;
lv_obj_t * ui_Fan1OFLabel2;
lv_obj_t * ui_Fan2Button2;
lv_obj_t * ui_Fan2OFLabel3;
void ui_event_HomeButton3(lv_event_t * e);
lv_obj_t * ui_HomeButton3;
lv_obj_t * ui_HomeLable3;
lv_obj_t * ui_HomeImage3;
lv_obj_t * ui_PowerButton3;
lv_obj_t * ui_StopButton3;
lv_obj_t * ui_StopLable3;
lv_obj_t * ui_StopImage3;
lv_obj_t * ui_Extruder4;
lv_obj_t * ui_Extruder1Text2;
lv_obj_t * ui_Extruder1Image2;
lv_obj_t * ui_Extruder1Temp2;
lv_obj_t * ui_Extruder5;
lv_obj_t * ui_Extruder2Text2;
lv_obj_t * ui_Extruder2Image2;
lv_obj_t * ui_Extruder2Temp5;
lv_obj_t * ui_HeadText4;
lv_obj_t * ui_HeadText5;
lv_obj_t * ui_GoButton1;
lv_obj_t * ui_Label10mmUp4;
lv_obj_t * ui_GoBackButton1;
lv_obj_t * ui_Label10mmUp5;
lv_obj_t * ui_StopButton1;
lv_obj_t * ui_Label10mmUp6;
lv_obj_t * ui_GoButton2;
lv_obj_t * ui_Label10mmUp7;
lv_obj_t * ui_GoBackButton2;
lv_obj_t * ui_Label10mmUp8;
lv_obj_t * ui_StopButton5;
lv_obj_t * ui_Label10mmUp9;
// CUSTOM VARIABLES 温度与挤出事件
void ui_event_GoButton1(lv_event_t * e);
void ui_event_GoBackButton1(lv_event_t * e);
void ui_event_StopButton1(lv_event_t * e);
void ui_event_GoButton2(lv_event_t * e);
void ui_event_GoBackButton2(lv_event_t * e);
void ui_event_StopButton5(lv_event_t * e);
void ui_event_Fan1Button2(lv_event_t * e);
void ui_event_Fan2Button2(lv_event_t * e);
void ui_event_SetTemp(lv_event_t * e);
void ui_event_ApplyButton1(lv_event_t * e);
void ui_event_ApplyButton2(lv_event_t * e);

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_browser_extruder[3] = {&ui_img_browser_extruder1_png, &ui_img_browser_extruder2_png, &ui_img_browser_extruder3_png};
const lv_img_dsc_t * ui_imgset_fan[1] = {&ui_img_fan1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_AxisButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AxisScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_AxisScreen_screen_init);
    }
}

void ui_event_TempButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TempScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_TempScreen_screen_init);
    }
}


//纤维轴事件---------------------------------------------------------------start
void ui_event_ResetButton1(lv_event_t * e)//复位
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Set1Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        motor_homing(1);
    }
}

void ui_event_Set1Button(lv_event_t * e)//就位
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Set2Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        motor_position(1);
    }
}

void ui_event_Up1Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CCW, 1);//上升1mm
    }
}

void ui_event_Up1Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CCW, 5);//上升5mm
    }
}

void ui_event_Up1Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CCW, 10);//上升10mm
    }
}

void ui_event_Down1Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CW, 1);//下降1mm
        //motor_send_command(1, CW, 16000);//8微分：1600步/圈/2mm，理论20mm,实际10mm（实际16微分）
        //motor_send_command(1, CW, 32000);//理论40mm，实际20mm
        //motor_send_command(1, CW, 64000);//理论80mm，实际40mm
    }
}

void ui_event_Down1Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CW, 5);//下降5mm
    }
}

void ui_event_Down1Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(1, CW, 10);//下降10mm
    }
}
//纤维轴事件-----------------------------------------------------------end

//树脂轴事件-----------------------------------------------------------start
void ui_event_ResetButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Set2Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}



void ui_event_Set2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Set1Button, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_HomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}
//树脂轴事件-----------------------------------------------------------end

//剪刀事件-----------------------------------------------------------start
void ui_event_CutterResetButton(lv_event_t * e)//剪刀复位
{   
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        cutter_send_command(K2_PIN,0);
    }
}

void ui_event_CutterDownButton(lv_event_t * e)//剪刀就位
{   
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        cutter_send_command(K1_PIN,0);
    }
}

void ui_event_CutterStopButton(lv_event_t * e)//剪刀停止
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        gpio_set_level(SW1_PIN,0);
        gpio_set_level(SW2_PIN,0);
        vTaskDelay(pdMS_TO_TICKS(100));
        gpio_set_level(SW1_PIN,1);
        gpio_set_level(SW2_PIN,1);
    }
}
//剪刀事件-----------------------------------------------------------end

//温度与挤出事件-----------------------------------------------------------start
//温度设置
void ui_event_SetTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SetExtruderTempPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Fan1Button2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Fan2Button2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Extruder4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Extruder5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_T1Enter1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_T1Enter1);
    }
}

void ui_event_T2Enter1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_T2Enter1);
    }
}

//纤维轴温度读取发送
void ui_event_ApplyButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {

        const char * input_text = lv_textarea_get_text(ui_T1Enter1);//从文本框读字符串

        if (input_text != NULL && strlen(input_text) > 0) {
            
            float target_temp = (float)atof(input_text);//字符串转浮点

            PID_send_command(1, target_temp, true);

            printf("设置纤维加热温度为: %.1f\n", target_temp);
        }
        else 
        {
            printf("输入为空，未发送指令\n");
        }
    }
}

//树脂轴温度读取发送
void ui_event_ApplyButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {

        const char * input_text = lv_textarea_get_text(ui_T2Enter1);//从文本框读字符串

        if (input_text != NULL && strlen(input_text) > 0) {
            
            float target_temp = (float)atof(input_text);//字符串转浮点

            PID_send_command(2, target_temp, true);

            printf("设置树脂加热温度为: %.1f\n", target_temp);
        }
        else 
        {
            printf("输入为空，未发送指令\n");
        }
    }
}

//挤出
//纤维头
void ui_event_GoButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(3, CCW, 500000000000000);
    }
}

void ui_event_GoBackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(3, CW, 500000000000000);
    }
}

void ui_event_StopButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(3, MOTOR_STOP, 0);
    }
}

//树脂头
void ui_event_GoButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(4, CW, 500000000000000);
    }
}

void ui_event_GoBackButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(4, CCW, 500000000000000);
    }
}

void ui_event_StopButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        motor_send_command_mm(4, MOTOR_STOP, 0);
    }
}

//纤维风扇
void ui_event_Fan1Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fan_send_command(FAN1);
    }
}

//树脂风扇
void ui_event_Fan2Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fan_send_command(FAN2);
    }
}
//温度与挤出事件-----------------------------------------------------------end

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SetExtruderTempPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Fan1Button2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Fan2Button2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Extruder5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Extruder4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_HomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();

     //ui逆时针旋转90度
     lv_disp_set_rotation(dispp, LV_DISP_ROT_90);

    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_AxisScreen_screen_init();
    ui_TempScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
